### ISSUE TITLE
运行think-cluster-reload-workers报错

### ISSUE THREAD

**Issue by mxh861001** [thinkjs/thinkjs#1018]
### ENV

OS Platform: windows

Node.js Version: 8.9.1

ThinkJS Version:3.2.6

### more description

开发模式下运行 process.send('think-cluster-reload-workers'); 后报错如下

### error message

```
Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at process.target.send (internal/child_process.js:588:16)
    at Logger.workerDispatch [as dispatch] (D:\work\wanba-new\node_modules\log4js\lib\log4js.js:148:11)
    at Logger._log (D:\work\wanba-new\node_modules\log4js\lib\logger.js:95:12)
    at Logger.(anonymous function) [as info] (D:\work\wanba-new\node_modules\log4js\lib\logger.js:127:14)
    at ConsoleLogger.info (D:\work\wanba-new\node_modules\think-logger3\src\adapter\base.js:16:26)
    at Object.logger (D:\work\wanba-new\src\config\adapter.js:34:33)
    at queryFn.catch.then.data (D:\work\wanba-new\node_modules\think-mysql\index.js:144:21)
    at tryCatcher (D:\work\wanba-new\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\work\wanba-new\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (D:\work\wanba-new\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (D:\work\wanba-new\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (D:\work\wanba-new\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (D:\work\wanba-new\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (D:\work\wanba-new\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (D:\work\wanba-new\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20) { request: 
   { method: 'GET',
     url: '/admin/system/index/?group=wechat',
     header: 
      { host: '127.0.0.1:8361',
        connection: 'keep-alive',
        'upgrade-insecure-requests': '1',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36',
        accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        referer: 'http://127.0.0.1:8361/admin/system/index/?group=wechat',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'zh-CN,zh;q=0.9',
        cookie: 'upNet=0.29; downNet=1.20; softType=2; phpmodel=%u5171%u751F%u6A21%u5F0F; rank=a; serverip=169.254.95.205; iplist=169.254.95.205; serverType=nginx-1.11.13; webSoft=D%3A%5Cwork-tools%5CServerAdmin%5CBtSoft%5CWebSoft; web=true; ftp=; mysql=true; sqlserver=false; Path=D%3A%5C%5C; memSize=; PCmemory=8074%2C2700; XiaoHU=c5ba70ee-c2c5-4005-b49f-cc3bc04ca008; xiaohu=d3b7dbdb-451a-4cc1-9669-a5bfecaba9c0' } },
  response: 
   { status: 404,
     message: 'Not Found',
     header: { 'x-powered-by': 'thinkjs-3.2.6', connection: 'close' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/admin/system/index/?group=wechat',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: channel closed
    at process.target.send (internal/child_process.js:588:16)
    at Logger.workerDispatch [as dispatch] (D:\work\wanba-new\node_modules\log4js\lib\log4js.js:148:11)
    at Logger._log (D:\work\wanba-new\node_modules\log4js\lib\logger.js:95:12)
    at Logger.(anonymous function) [as error] (D:\work\wanba-new\node_modules\log4js\lib\logger.js:127:14)
    at ConsoleLogger.error (D:\work\wanba-new\node_modules\think-logger3\src\adapter\base.js:24:26)
    at process.on.err (D:\work\wanba-new\node_modules\think-cluster\lib\worker.js:109:20)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process.emit (D:\work\wanba-new\node_modules\source-map-support\source-map-support.js:439:21)
    at process._fatalException (bootstrap_node.js:374:26)
```

**Comment by mxh861001** [comment]
发现开发模式下关闭mysql的日志信息后,运行正常
```js
exports.model = {
  type: 'mysql',
  common: {
    logConnect: false,
    logSql: false,
    logger: msg => think.logger.info(msg)
  },
  mysql: {
    ....
  }
};
```

**Comment by welefen** [comment]
@mxh861001 think-cluster-reload-workers 这个指令是什么策略下触发的呢？这个错误是因为 log4js 要把日志发给 master，但此时 IPC 被关闭了。

**Comment by mxh861001** [comment]
@welefen 系统配置更改后重启

**Comment by welefen** [comment]
这个问题是 IPC 关闭时，log4js 发送消息导致的，暂时关闭
