### ISSUE TITLE
thinkjs-cli运行报错

### ISSUE THREAD

**Issue by lgl1993** [thinkjs/thinkjs#1056]
## DESC
internal/child_process.js:317
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:317:11)
    at exports.spawn (child_process.js:471:9)
    at Command.executeSubCommand (/usr/local/lib/node_modules/think-cli/node_modules/commander/index.js:564:14)
    at Command.parse (/usr/local/lib/node_modules/think-cli/node_modules/commander/index.js:489:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/think-cli/bin/thinkjs:19:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
### ENV

OS Platform:
mac
Node.js Version:
7.0
ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```
全局安装了thinkjs-cli,但是怎么运行都报这个错。
### more description

// your detail description

**Comment by berwin** [comment]
@lgl1993  请问cli是什么版本？？？

**Comment by lgl1993** [comment]
权限问题，我把thinkjs-cli的权限改了，就好了。
