### ISSUE TITLE
npm start  时 出现这个错误

### ISSUE THREAD

**Issue by roycms** [thinkjs/thinkjs#1058]
```
[2018-01-19T04:15:54.045] [12618] [INFO] - Workers: 1
/home/pi/www/app/logic/.AppleDouble/index.js:1
(function (exports, require, module, __filename, __dirname) { 
                                                              

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at exports.interopRequire (/home/pi/www/node_modules/think-loader/loader/util.js:14:13)
    at files.forEach.file (/home/pi/www/node_modules/think-loader/loader/common.js:16:26)
    at Array.forEach (<anonymous>)
    at Object.loadFiles (/home/pi/www/node_modules/think-loader/loader/common.js:12:11)
    at Object.load (/home/pi/www/node_modules/think-loader/loader/common.js:64:32)
    at Loader.loadLogic (/home/pi/www/node_modules/think-loader/index.js:55:19)
    at thinkLoader.loadData (/home/pi/www/node_modules/thinkjs/lib/loader.js:44:37)


```

**Comment by roycms** [comment]
找到原因了  AppleDouble 是苹果系统生的隐藏文件，超级恶心，苹果在访问nas存储器时会在目录下存在这个文件夹和当前目录的一份文件
