### ISSUE TITLE
iisnode部署时出现ENOTSUP

### ISSUE THREAD

**Issue by sunwu7096** [thinkjs/thinkjs#1072]
问下大家,iisnode部署时如何解决这个问题:
Application has thrown an uncaught exception and is terminated:
Error: write ENOTSUP
at exports._errnoException (util.js:1018:11)
at ChildProcess.target._send (internal/child_process.js:668:20)
at ChildProcess.target.send (internal/child_process.js:552:19)
at sendHelper (cluster.js:753:15)
at send (cluster.js:535:12)
at cluster.js:510:7
at SharedHandle.add (cluster.js:99:3)
at queryServer (cluster.js:502:12)
at Worker.onmessage (cluster.js:451:7)
at ChildProcess. (cluster.js:767:8)
at emitTwo (events.js:111:20)
at ChildProcess.emit (events.js:191:7)
at process.nextTick (internal/child_process.js:758:12)
at _combinedTickCallback (internal/process/next_tick.js:73:7)
at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by welefen** [comment]
@sunwu7096 你创建个 DEMO 项目直接部署也是这样的么？

**Comment by lizheming** [comment]
close with long no activity.
