### ISSUE TITLE
数据库连接异常无法在业务层 catch

### ISSUE THREAD

**Issue by zheeeng** [thinkjs/thinkjs#1098]
## DESC

在 Controller 中查询数据库，该数据库无法连接，在 Controller 中可以 catch 一次，但在 Controller 外仍然会被 thinkjs 抛出。

### ENV

OS Platform: OSX 10.11.6

Node.js Version: v8.5

ThinkJS Version: 2.2

### code

```js
// controller
export default class extends think.controller.base {
    async usersAction () {
        try {
            const model = this.model('users') // config 中的 db 未启动
            const data = await model.select() // 此行将会报错，数据库无法连接
            return this.json(data)
        } catch (e) { // 数据库无法连接的异常可以捕获
            return this.deny(500)
        }
    }
}
```

在 Controller 内可以捕获一次，但 thinkjs 还是把这个错误抛了出来（见下方）。在 congtroller catch 异常的时候如果打印出异常，和下面的的异常内容是一样的。也就是说，这个异常被抛了两次，第一次可以 catch，第二个无法在业务层被解决。

### error message

```
[HTTP] GET /api/users 500 22ms
[2018-02-28 14:07:37] [Error] Error: Connection refused, mongodb://localhost:27017/users. http://www.thinkjs.org/doc/error_message.html#econnrefused
    at _class.run (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/lib/util/await.js:52:40)
    at Object.think.await (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/lib/core/think.js:1032:25)
    at _class._callee$ (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/lib/adapter/socket/mongo.js:120:59)
    at tryCatch (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/node_modules/babel-runtime/regenerator/runtime.js:121:21)
    at step (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
    at tryCatcher (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/Zheeeng/Workspace/pandora/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
```

### more description

// your detail description

**Comment by welefen** [comment]
@zheeeng 这个不是没有捕获到错误，只是这个错误信息在控制台下打印出来。
2.x 里有些错误如果用户没有处理的话会导致看不到错误信息，导致排查比较麻烦，所以有些关键错误是强制打印出来的。3.0 版本里已经改进了这种处理方式

**Comment by lizheming** [comment]
close with no activity
