### ISSUE TITLE
关于上传文件参数配置

### ISSUE THREAD

**Issue by smallage** [thinkjs/thinkjs#1105]
## DESC
 关于上传文件限制文件大小的配置问题
### ENV

OS Platform:
win10
Node.js Version:
v8.9.3
ThinkJS Version:
2.2.1
### code

```js
let video = this.file('video');
```

### error message

```
Error: maxFileSize exceeded, received 2113385 bytes of file data
```

### more description

// your detail description 
 我像上传一个大文件，但是提示我文件过大，然后我再thinkjs里面和文档里没找到关于上传文件大小限制这个参数

**Comment by wurining** [comment]
https://github.com/thinkjs/think-payload#options

**Comment by joe434200** [comment]
我页是这个错误
`Error: maxFileSize exceeded, received 2103512 bytes of file data
    at Stream.<anonymous> (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/incoming_form.js:222:19)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at MultipartParser.parser.onPartData (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/incoming_form.js:387:14)
    at callback (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/multipart_parser.js:102:31)
    at dataCallback (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/multipart_parser.js:112:11)
    at MultipartParser.write (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/multipart_parser.js:305:3)
    at IncomingForm.write (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/incoming_form.js:159:34)
    at IncomingMessage.<anonymous> (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/incoming_form.js:125:12)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at IncomingMessage.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) `

然后我的配置
`    {
        handle: payload,//对上传文件进行处理
        options: {
            limit : 1024*1024*10,
        }
    },`

还是这个问题

系统环境
ubuntu16.04
node-8.10.0
thinkjs-3.2.5

尚未解决
@wurining 
@smallage 
@welefen

**Comment by welefen** [comment]
@joe434200 这是个依赖的 formidable 升级了加了限制策略导致的，我们升级下 think-payload

**Comment by berwin** [comment]
think-payload 已经升级到3.0版本，可以更新下依赖并修改配置调整大小限制，如下：

```javascript
{
  handle: payload,
  options: {
    multipart: { // form data 类型请求相关配置参数，主要用于文件上传
      maxFileSize: 1024 * 1024 * 1024
    }
  }
}
```

**Comment by joe434200** [comment]
我已经找到了，似乎不是maxFileSize 吧 ，是maxFieldSize？？ @
