### ISSUE TITLE
maxFileSize exceeded

### ISSUE THREAD

**Issue by joe434200** [thinkjs/thinkjs#1108]
## DESC
上传文件
服务器error，页面看到的结果是500错误，并不是413

### ENV
OS Platform:
ubuntu-16.04

Node.js Version:
node-8.10.0
ThinkJS Version:
thinkjs-3.2.6

### code

```js
// middleware.js的配置
{
        handle: payload,//对上传文件进行处理
        options: {
            limit : 1024*1024*1024,

        }
    },
```

### error message

```
// your error message here
Error: maxFileSize exceeded, received 2102441 bytes of file data
    at Stream.<anonymous> (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/incoming_form.js:222:19)
    at emitOne (events.js:116:13)
    at Stream.emit (events.js:211:7)
    at MultipartParser.parser.onPartData (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/incoming_form.js:387:14)
    at callback (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/multipart_parser.js:102:31)
    at dataCallback (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/multipart_parser.js:115:11)
    at MultipartParser.write (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/multipart_parser.js:237:15)
    at IncomingForm.write (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/incoming_form.js:159:34)
    at IncomingMessage.<anonymous> (/web/app/ming/node_modules/_formidable@1.2.0@formidable/lib/incoming_form.js:125:12)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at IncomingMessage.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) 
```

### more description
尝试改了middleware中的payload limit，改了很久，感觉并不起作用，也不是nginx的问题，已经跳过nginx来做测试。。

**Comment by chianquan** [comment]
我这里也遇到这个问题，本地的时候没问题，构建环境上有问题
查了下，发现在think-payload的版本依赖中 要求formidable为^1.1.1版本，我本地下载到的版本是1.1.1没出现该问题，
而构建环境上的版本却是1.2.0，导致多了一个文件大小的判断的，默认为2M，超过则会报错

查看了package-lock.json文件，里面写的是1.1.1版本，目前不明白为何构建环境上的版本没有按package-lock的版本的原因。（有可能是环境脚本做了特殊处理的原因）

**Comment by welefen** [comment]
这是因为 `formidable` 包在 1.2.0 版本时加了个 `maxFileSize` 参数，默认为 2MB，在 1.2.1 版本时又改为 20MB 了，需要配置下这个参数，如：

```js
{
        handle: payload,//对上传文件进行处理
        options: {
            limit : 1024*1024*1024,
            maxFileSize:  200 * 1024 * 1024
        }
    },
```

**Comment by berwin** [comment]
think-payload 已经升级到3.0版本，可以更新下依赖并修改配置调整大小限制，如下：

```javascript
{
  handle: payload,
  options: {
    multipart: { // form data 类型请求相关配置参数，主要用于文件上传
      maxFileSize: 1024 * 1024 * 1024
    }
  }
}
```

**Comment by chianquan** [comment]
嗯，是这样的。我们这边美按package-lock获取版本也确定了，是构建服务优化这里构建的时候美使用其中的package-lock文件的原因，问题已解决
