### ISSUE TITLE
关联模型更新失败

### ISSUE THREAD

**Issue by lscho** [thinkjs/thinkjs#1109]
## 说明
重新 `npm install` 出现，之前无问题。

## 关联配置
```javascript
  get relation() {
    return {
      category: {
        type: think.Model.BELONG_TO,
        model: 'meta',
        key: 'category_id',
        fKey: 'id',
        field: 'id,name,slug,description,count'
      },
      tag: {
        type: think.Model.MANY_TO_MANY,
        model: 'meta',
        rModel: 'relationships',
        rfKey: 'meta_id',
        key: 'id',
        fKey: 'content_id',
        field: 'id,name,slug,description,count'
      }
    };
  }
```

## 错误信息
```
[2018-03-18T00:29:01.506] [6105] [ERROR] - TypeError: Cannot read property 'id' of undefined
    at getSchema.then.schema (/home/lscho/www/blog/server/node_modules/_think-model-abstract@1.2.1@think-model-abstract/lib/schema.js:53:17)
    at tryCatcher (/home/lscho/www/blog/server/node_modules/_bluebird@3.3.5@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/lscho/www/blog/server/node_modules/_bluebird@3.3.5@bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/lscho/www/blog/server/node_modules/_bluebird@3.3.5@bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/lscho/www/blog/server/node_modules/_bluebird@3.3.5@bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/lscho/www/blog/server/node_modules/_bluebird@3.3.5@bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/home/lscho/www/blog/server/node_modules/_bluebird@3.3.5@bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/lscho/www/blog/server/node_modules/_bluebird@3.3.5@bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/lscho/www/blog/server/node_modules/_bluebird@3.3.5@bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

```

**Comment by lscho** [comment]
多谢，参考给的连接[https://github.com/thinkjs/thinkjs/issues/1107](https://github.com/thinkjs/thinkjs/issues/1107) 已解决，是put请求，确实是数据里缺少主键。
