### ISSUE TITLE
使用 increment 方法单独更新某个字段值也会触发关联模型的更新，导致报错

### ISSUE THREAD

**Issue by lscho** [thinkjs/thinkjs#1114]
关联配置
```javascript
  // 模型关联
  get relation() {
    return {
      category: {
        type: think.Model.BELONG_TO,
        model: 'meta',
        key: 'category_id',
        fKey: 'id',
        field: 'id,name,slug,description,count'
      },
      tag: {
        type: think.Model.MANY_TO_MANY,
        model: 'meta',
        rModel: 'relationships',
        rfKey: 'meta_id',
        key: 'id',
        fKey: 'content_id',
        field: 'id,name,slug,description,count'
      },
      comment: {
        type: think.Model.HAS_MANY,
        key: 'id',
        fKey: 'content_id'
      }
    };
  }
```

更新字段值

```javascript
this.modelInstance.where(map).increment('view');
```

报错
```
[2018-03-21T15:04:10.932] [6511] [INFO] - SQL: UPDATE `ls_content` SET `view`=`view`+1 WHERE ( `slug` = 'closure' ) AND ( `status` = 99 ), Time: 9ms
[2018-03-21T15:04:10.940] [6511] [ERROR] - unhandledRejection, times: 1, pid: 6511
[2018-03-21T15:04:10.940] [6511] [ERROR] - TypeError: model.getSchema is not a function
    at /home/lscho/www/blog/server/node_modules/_think-model@1.2.0@think-model/lib/relation/has_many.js:42:23
    at Generator.next (<anonymous>)
    at step (/home/lscho/www/blog/server/node_modules/_think-model@1.2.0@think-model/lib/relation/has_many.js:1:191)
    at /home/lscho/www/blog/server/node_modules/_think-model@1.2.0@think-model/lib/relation/has_many.js:1:437
    at Promise._execute (/home/lscho/www/blog/server/node_modules/_bluebird@3.3.5@bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/lscho/www/blog/server/node_modules/_bluebird@3.3.5@bluebird/js/release/promise.js:473:18)
    at new Promise (/home/lscho/www/blog/server/node_modules/_bluebird@3.3.5@bluebird/js/release/promise.js:77:14)
    at /home/lscho/www/blog/server/node_modules/_think-model@1.2.0@think-model/lib/relation/has_many.js:1:99
    at HasManyRelation.setRelationData (/home/lscho/www/blog/server/node_modules/_think-model@1.2.0@think-model/lib/relation/has_many.js:59:7)
    at /home/lscho/www/blog/server/node_modules/_think-model@1.2.0@think-model/lib/relation/relation.js:92:25
    at Array.map (<anonymous>)
    at /home/lscho/www/blog/server/node_modules/_think-model@1.2.0@think-model/lib/relation/relation.js:88:52
    at Generator.next (<anonymous>)
    at step (/home/lscho/www/blog/server/node_modules/_think-model@1.2.0@think-model/lib/relation/relation.js:1:191)
    at /home/lscho/www/blog/server/node_modules/_think-model@1.2.0@think-model/lib/relation/relation.js:1:437
    at Promise._execute (/home/lscho/www/blog/server/node_modules/_bluebird@3.3.5@bluebird/js/release/debuggability.js:272:9)

```

猜测是因为更新数据中没有主键吗？是否应该对更新操作数据检测一下，不存在主键就不触发关联模型的更新？

**Comment by lizheming** [comment]
@lscho 之前已经加了，只是还没有发版，你更新到 think-model@1.2.1 试一下

**Comment by lscho** [comment]
更新之后还是报错，看了一下 update 部分的代码，似乎没有变化。使用 increment 单独更新字段值的话，还是会触发关联模型的更新

用了`think.Model.HAS_MANY`就会报错。
`think.Model.BELONG_TO`和`think.Model.MANY_TO_MANY`不报错，但是控制台看到相关的sql语句执行了，而且条件值为`undefined`，而且控制台会打印一个
```json这样的信息
{ code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0 }

```

**Comment by lizheming** [comment]
没仔细看那个错误，才发现是另外一个问题，已经更新，并增加了关联数据的判断（之前只是增加了关联数据是否有主键的判断），我这边本地实测没问题了，你更新到 `think-model@1.2.2` 再试试。

**Comment by lscho** [comment]
@lizheming 测试正常，感谢！
