### ISSUE TITLE
用hprose-nodejs做客户端，解析报错

### ISSUE THREAD

**Issue by muunnw** [thinkjs/thinkjs#1115]
## DESC
用hprose-nodejs做客户端调用hprose服务器

```
const hprose = require('hprose');
module.exports = class extends Base {
    async indexAction() {
        var client = new hprose.HttpClient('http://localhost:8086/', ['hello']);

        return await client.hello(function () {
            console.log(1);
        }, function () {
            console.log(2);
        });
    }
};
```
放在thinkjs框架下就会报错
```
> 2
{ Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:359:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20) bytesParsed: 238, code: 'HPE_UNEXPECTED_CONTENT_LENGTH' } 
```

### ENV

OS Platform:
mac

Node.js Version:
v6.2.0

ThinkJS Version:
v3.2.7

**Comment by welefen** [comment]
这是 hprose 报的错，跟 ThinkJS 没有关系。

http://localhost:8086/ 这个服务是存在的？
