### ISSUE TITLE
think-model-mysql设置schema无效

### ISSUE THREAD

**Issue by suen427** [thinkjs/thinkjs#1121]
### creation设置的default无效

OS Platform: macOS

Node.js Version:8.9

ThinkJS Version:3.2.7

### code

```js
get schema() {
    return {
      id: { // 字段名称
        type: 'int(11)',
        primary: true,
        autoIncrement:true
      },
      name: {
        type: 'varchar(45)',
        required: true
      },
      perm: {
        type: 'varchar(64)',
        required: true
      },
      creation: {
        type: 'datetime',
        default: function(){return think.datetime()} // default 为一个函数
      },
      last_modified: {
        type: 'datetime',
        default: function(){return think.datetime()}, // default 为一个函数,
        update:true
      },
      description: {
        type: 'varchar(128)'
      }
    }
  }
```

### error message

```
{ Error: ER_NO_DEFAULT_FOR_FIELD: Field 'creation' doesn't have a default value
    at Query.Sequence._packetToError (/Users/sunhua/Workspace/sunhua/rob/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/sunhua/Workspace/sunhua/rob/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/sunhua/Workspace/sunhua/rob/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/sunhua/Workspace/sunhua/rob/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/sunhua/Workspace/sunhua/rob/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/sunhua/Workspace/sunhua/rob/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### more description

感觉获取schame的方法没有去读取设置的配置
```js
/**
   * get table schema
   * @param {String} table 
   */
  getSchema(table = this.table) {
    if (SCHEMAS[table]) return Promise.resolve(SCHEMAS[table]);
    return debounce.debounce(`getTable${table}Schema`, () => {
      const columnSql = `SHOW COLUMNS FROM ${this.parser.parseKey(table)}`;
      return this.query.query(columnSql).catch(() => []).then(data => {
        let ret = {};
        data.forEach(item => {
          ret[item.Field] = {
            name: item.Field,
            type: item.Type,
            required: item.Null === '',
            default: '',
            primary: item.Key === 'PRI',
            unique: item.Key === 'UNI',
            autoIncrement: item.Extra.toLowerCase() === 'auto_increment'
          };
        });
        ret = helper.extend(ret, this.schema);
        for (const key in ret) {
          ret[key] = this._parseItemSchema(ret[key]);
        }
        SCHEMAS[table] = ret;
        return ret;
      });
    });
  }
```

**Comment by suen427** [comment]
我把getSchema方法改成下面这样就好了
```js
        ret = helper.extend(ret, think.model(table).schema);
        for (const key in ret) {
          ret[key] = this._parseItemSchema(ret[key]);
        }
        SCHEMAS[table] = ret;
```

**Comment by lizheming** [comment]
我看代码 schema 是有传进来的 https://github.com/thinkjs/think-model-abstract/blob/master/index.js#L21 `this.schema` 应该就是 `think.model(table).schema`。
