### ISSUE TITLE
think-cache-redis不支持redis集群

### ISSUE THREAD

**Issue by shangxianfeng** [thinkjs/thinkjs#1124]
## DESC
连接redis集群时报错如下:
```js
{ ReplyError: MOVED 13007 127.0.0.1:7002
    at JavascriptReplyParser.returnError (E:\work\GitLab\Shinezone-GameServerDev\SIM-Server\node_modules\ioredis\lib\redis\parser.js:25:25)
    at JavascriptReplyParser.run (E:\work\GitLab\Shinezone-GameServerDev\SIM-Server\node_modules\ioredis\node_modules\redis-parser\lib\javascript.js:135:18)
    at JavascriptReplyParser.execute (E:\work\GitLab\Shinezone-GameServerDev\SIM-Server\node_modules\ioredis\node_modules\redis-parser\lib\javascript.js:112:10)
    at Socket.<anonymous> (E:\work\GitLab\Shinezone-GameServerDev\SIM-Server\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'ReplyError',
  message: 'MOVED 13007 127.0.0.1:7002',
  command: { name: 'get', args: [ 'Sharding:user:1000000' ] } } { request:
   { method: 'POST',
     url: '/game/load',
     header:
      { 'content-type': 'application/json',
        'accept-language': 'zh',
        'cache-control': 'no-cache',
        'postman-token': '309eac62-b5ff-455c-a56a-ab318997a87a',
        'user-agent': 'PostmanRuntime/7.1.1',
        accept: '*/*',
        host: 'localhost:8360',
        cookie: 'thinkjs=f0b47152-c0d7-4762-a796-81ece0a3a752',
        'accept-encoding': 'gzip, deflate',
        'content-length': '551',
        connection: 'keep-alive' } },
  response:
   { status: 200,
     message: 'OK',
     header: { 'x-powered-by': 'thinkjs-3.2.6' } },
  app: { subdomainOffset: 2, proxy: true, env: 'production' },
  originalUrl: '/game/load',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
```
### ENV

OS Platform: Windows10

Node.js Version:  v8.9.2

ThinkJS Version: 3.2.6

### code

adapter配置
```js
/**
 * cache adapter config
 * @type {Object}
 */
exports.cache = {
  type: 'redis',
  common: {
    timeout: 24 * 60 * 60 * 1000 // millisecond
  },
  redis: {
    handle: redisCache,
    port: 7000,
    host: '127.0.0.1',
    password: '',
    gcInterval: 24 * 60 * 60 * 1000 // gc interval
  }
};
```

### error message

```
ReplyError: MOVED 13007 127.0.0.1:7002
```

### more description

我们使用thinkjs来开发游戏服务器, 需要使用reids集群作缓存, think-cache-redis 好像不支持redis集群。

请问能不能让think-cache-redis支持redis集群呢， 如果短期内不能的话，希望给一些建议以便于我们自已修改。

**Comment by lushijie** [comment]
think-cache-redis 不支持redis集群。
如果只是采用多个redis服务器存储的话，可以采用多个redis配置。
如果要真正实现cluster、sentinel集群方式，可以使用ioredis实现一个cache的adapter。

**Comment by shangxianfeng** [comment]
@lushijie 我们准备使用cluster集群方式，看来需要实现一个新的adapter。非常感谢！
