### ISSUE TITLE
thinkjs module 报错

### ISSUE THREAD

**Issue by imhan1988** [thinkjs/thinkjs#1154]
## DESC
新建模块
thinkjs module 模块名 ， 会报错
### ENV

OS Platform:macOS 10.12.5 

Node.js Version: v8.9.4

Think-cli Version:2.2.3

### code

```js
// your code here
```

### error message

```
// your error message here
/usr/local/lib/node_modules/think-cli/lib/run.js:17
    this._cacheTemplatePath = path.join(config.templateCacheDirectory, this.options.template.replace(/[\\/\\:]/g, '-'));
                                                                                             ^

TypeError: Cannot read property 'replace' of undefined
    at new Run (/usr/local/lib/node_modules/think-cli/lib/run.js:17:94)
    at Object.<anonymous> (/usr/local/lib/node_modules/think-cli/bin/thinkjs-module:72:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at `bootstrap_node.js:608:3`
```

### more description

// your detail description

**Comment by berwin** [comment]
@imhan1988 请问下，你的项目package.json里thinkjs下面是否存在 templateName ？如果存在 templateName的值是什么？

**Comment by imhan1988** [comment]
@berwin 没有templateName

**Comment by berwin** [comment]
@imhan1988 噢噢噢。了解了，再问一个问题。您的项目是使用think-cli 2.0以上版本创建的还是使用1.0创建的？

**Comment by imhan1988** [comment]
@berwin 刚看了下，是2.2.3

**Comment by berwin** [comment]
@imhan1988 这个问题已经修复，很抱歉对此带来的不便~
