### ISSUE TITLE
关于调用service 报错的问题

### ISSUE THREAD

**Issue by twbmg** [thinkjs/thinkjs#1176]
## DESC
调用service下面的方法找不到

### ENV

OS Platform:
win10
Node.js Version:
v8.9.3
ThinkJS Version:
 v2.2.24
### code
在  cms/src/home/service/sms.js 定义
```js
'use strict';

export default class extends think.service.base {
    constructor(key, secret,http) {
        super(http);
        this.key = key;
        this.secret = secret;
        console.log(111111);
    }
    aa() {
        console.log(2222);
    }
}
```
在 cms/src/home/controller/index.js 调用
```js
export default class extends Base {
    /**
     * index action
     * @return {Promise} []
     */
    async indexAction() {
        const sms = await think.service('sms', 'home');
        console.log(sms.aa());
        this.test();
        // await sms.aa();
        //auto render template file index_index.html
        return this.display();
    }

    test() {
        console.info('test')
    }
}
```

### error message

```
// your error message here
[2018-05-28 17:09:42] [Error] TypeError: sms.aa is not a function
    at _class._callee$ (C:\NodeProject\cms\src\home\controller\index.js:11:25)
    at tryCatch (C:\NodeProject\cms\node_modules\_regenerator-runtime@0.11.1@regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\NodeProject\cms\node_modules\_regenerator-runtime@0.11.1@regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\NodeProject\cms\node_modules\_regenerator-runtime@0.11.1@regenerator-runtime\runtime.js:114:21)
    at step (C:\NodeProject\cms\node_modules\_babel-runtime@6.26.0@babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\NodeProject\cms\node_modules\_babel-runtime@6.26.0@babel-runtime\helpers\asyncToGenerator.js:28:13
    at <anonymous>
```

### more description

// your detail description

**Comment by lizheming** [comment]
```js
const smsService = think.service('sms', 'home')
const sms = new smsService();

sms.aaa();
```
