### ISSUE TITLE
出现这个问题是怎么了 npm start 时 

### ISSUE THREAD

**Issue by roycms** [thinkjs/thinkjs#1232]
/alidata/gameServer/node_modules/think-trace/lib/tracer.js:55
  async getTemplateContent() {
        ^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/alidata/gameServer/node_modules/think-trace/lib/index.js:4:16)
    at Module._compile (module.js:570:32)

**Comment by roycms** [comment]
知道什么原因了 node 的版本是6.9.0 的有点低，官方说的大于6.x.0 这个太低了，应该是8.x 以上了

**Comment by lizheming** [comment]
嗯，是的 https://github.com/koajs/koa/blob/master/package.json#L60 依赖了 koa 以它的为准
