### ISSUE TITLE
关于think-mysql

### ISSUE THREAD

**Issue by 977277822** [thinkjs/thinkjs#1236]
不知道是不是配置原因，mysql在使用一段时间后就会断开连接

```js
Error: Pool is closed.
    at Pool.getConnection (/opt/apps/other/node_modules/mysql/lib/Pool.js:25:15)
    at Promise (/opt/apps/other/node_modules/think-helper/index.js:83:10)
    at Promise._execute (/opt/apps/other/node_modules/thinkjs/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/opt/apps/other/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/opt/apps/other/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:77:14)
    at args (/opt/apps/other/node_modules/think-helper/index.js:82:12)
    at ThinkMysql.getConnection (/opt/apps/other/node_modules/think-mysql/index.js:72:73)
    at debounceInstance.debounce (/opt/apps/other/node_modules/think-mysql/index.js:208:21)
    at Debounce.debounce (/opt/apps/other/node_modules/think-debounce/index.js:18:30)
    at ThinkMysql.query (/opt/apps/other/node_modules/think-mysql/index.js:207:31)
    at MysqlQuery.query (/opt/apps/other/node_modules/think-model-abstract/lib/query.js:22:29)
    at MysqlQuery.select (/opt/apps/other/node_modules/think-model-abstract/lib/query.js:150:29)
    at Mysql.select (/opt/apps/other/node_modules/think-model-abstract/index.js:88:23)
    at /opt/apps/other/node_modules/think-model/lib/model.js:609:38
    at Generator.next (<anonymous>)
    at step (/opt/apps/other/node_modules/think-model/lib/model.js:1:191) code: 'POOL_CLOSED' } { request:
```
这是mysql配置
数据库本身的性能应该问题不大，一共只开了两个worker，服务器访问频率也不高
```js
handle: mysql,
    database: ,
    prefix: '',
    encoding: 'utf8',
    host: ,
    port: ,
    user: ,
    password:,
    connectionLimit: 2,
    dateStrings: true,
    charset: 'utf8mb4'
```

**Comment by 977277822** [comment]
补充一下：
"think-model": {
      "version": "1.2.2",
      "resolved": "http://registry.npm.taobao.org/think-model/download/think-model-1.2.2.tgz",
      "integrity": "sha1-e7+0LrqkpFxCgcfvy0YptK7UJyk=",
      "requires": {
        "think-cache": "1.1.0",
        "think-debounce": "1.0.3",
        "think-helper": "1.0.22",
        "think-model-abstract": "1.2.1"
      }
    },
    "think-model-abstract": {
      "version": "1.2.1",
      "resolved": "http://registry.npm.taobao.org/think-model-abstract/download/think-model-abstract-1.2.1.tgz",
      "integrity": "sha1-zizVbLQohkUjOXIAZ4aHG5c8oOg=",
      "requires": {
        "babel-preset-think-node": "1.0.3",
        "debug": "3.1.0",
        "think-helper": "1.0.22",
        "think-mysql": "1.2.4"
      }
    },
    "think-model-mysql": {
      "version": "1.0.6",
      "resolved": "http://registry.npm.taobao.org/think-model-mysql/download/think-model-mysql-1.0.6.tgz",
      "integrity": "sha1-lJJbwDxMpA0K7KNVJmIAoAUppVI=",
      "requires": {
        "think-debounce": "1.0.3",
        "think-helper": "1.0.22",
        "think-model-abstract": "1.2.1",
        "think-mysql": "1.2.4"
      }
    },

**Comment by 977277822** [comment]
@akira-cn 月影大大，这个问题还蛮麻烦的，持续不断连接中断无法重连，导致服务一直不稳定宕机，麻烦找个时间排查一下这个问题。。。

**Comment by 977277822** [comment]
对了，用的是mysql-session模块

**Comment by welefen** [comment]
@977277822 大概多长时间会断开，看下数据库的超时配置时间。可以参考这里： https://www.cnblogs.com/xiaoboluo768/p/6222862.html

**Comment by welefen** [comment]
项目里有其他地方用了 `think-mysql` 模块，然后在某些情况下调用了 close 方法么？

**Comment by 977277822** [comment]
项目里用了think-mysql-session 模块，换了其他的session类型之后，就没有再出现think-mysql close的情况了

**Comment by welefen** [comment]
@977277822 恩，是 think-session-mysql 模块有些问题，已经修复了。升级下 think-mysql-session@2.0.0 和 think-session@1.1.1，另：数据表中加个 maxage 字段，具体见：https://github.com/thinkjs/think-session-mysql#create-database

**Comment by 977277822** [comment]
@welefen  npmjs 里的提示没修改~   建议修改一下

npmjs -> think-session-mysql
DROP TABLE IF EXISTS `think_session`;
  CREATE TABLE `think_session` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `cookie` varchar(255) NOT NULL DEFAULT '',
    `data` text,
    `expire` bigint(11) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `cookie` (`cookie`),
    KEY `expire` (`expire`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by welefen** [comment]
think-session-mysql@2.0.1
