### ISSUE TITLE
think-websocket-ws 按照doc来走不通，服务端报404错误

### ISSUE THREAD

**Issue by klwfwdk** [thinkjs/thinkjs#1242]
### ENV

OS Platform:
centos7
Node.js Version:
v10.9.0
ThinkJS Version:
think-cli 2.2.5
### code
全部按照文档配置
```js
//src/controller/ws
module.exports = class extends think.Controller {
  constructor(...arg) {
    super(...arg);
  }
  openAction() {
    console.log('ws open');
    return this.success();
  }
  closeAction() {
    console.log('ws close');
    return this.success();
  }
  addUserAction() {
    console.log('addUserAction ...');
    console.log(this.wsData); // this.req.websocketData, 'thinkjs'
    console.log(this.websocket); // this.req.websocket, websocket instance
    console.log(this.isWebsocket); // this.isMethod('WEBSOCKET'), true
    return this.success();
  }
}
```

### error message

```
{ NotFoundError: url `/ws` not found.
    at Object.throw (/root/demo/node_modules/koa/lib/context.js:96:11)
    at beforeTrace.then.then (/root/demo/node_modules/think-trace/lib/index.js:33:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) message: 'url `/ws` not found.' } { request:
   { method: 'GET',
     url: '/ws',
     header:
      { host: '127.0.0.1:8360',
        connection: 'Upgrade',
        pragma: 'no-cache',
        'cache-control': 'no-cache',
        upgrade: 'websocket',
        origin: 'file://',
        'sec-websocket-version': '13',
        'user-agent':
         'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'zh-CN,zh;q=0.9',
        'sec-websocket-key': 'YWF/NoTngXlaiV2Fy2JP4A==',
        'sec-websocket-extensions': 'permessage-deflate; client_max_window_bits' } },
  response:
   { status: 404,
     message: 'Not Found',
     header: { 'x-powered-by': 'thinkjs-3.2.8' } },
  app: { subdomainOffset: 2, proxy: true, env: 'production' },
  originalUrl: '/ws',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
// your error message here
```

### more description
新手求教，完全按照文档来走不通，是否是缺少配置？

**Comment by klwfwdk** [comment]
我使用的是ws模块而不是socket.io模块，所以按照https://github.com/thinkjs/think-websocket-ws来配置
刚刚尝试额外安装配置了think-websocket模块 但是重启项目提示  think-websocket/index.js 的第七行 
`app.on`中的on未定义

**Comment by klwfwdk** [comment]
刚刚尝试了 的确是这个问题 问题已经解决 ，谢谢
