### ISSUE TITLE
查询经常会返回ResourceRequest timed out

### ISSUE THREAD

**Issue by shihuojian** [thinkjs/thinkjs#1261]
查询经常会返回ResourceRequest timed out，设置了超时时间也还是这样，求解

**Comment by welefen** [comment]
提供下更详细的错误信息

**Comment by shihuojian** [comment]
@welefen
`{ TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (E:\118.178.58.183\api-huadan\node_modules\_generic-pool@3.4.2@generic-pool\lib\ResourceRequest.js:62:17)
    at Timeout.bound (E:\118.178.58.183\api-huadan\node_modules\_generic-pool@3.4.2@generic-pool\lib\ResourceRequest.js:8:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'TimeoutError' }
`

**Comment by welefen** [comment]
项目里用了哪些模块，可以把 session 相关的模块都升级下试试。

**Comment by shihuojian** [comment]
@welefen 升级了还是一样

**Comment by shihuojian** [comment]
@welefen generic-pool 是不是这个模块的问题

**Comment by welefen** [comment]
把项目的 package 里依赖的模块，已经安装的版本贴下。

**Comment by shihuojian** [comment]
@welefen 
` "dependencies": {
    "ali-oss": "^6.0.1",
    "async": "^2.6.1",
    "crypto-js": "^3.1.9-1",
    "jsonwebtoken": "^8.3.0",
    "kcors": "^2.2.2",
    "lodash": "^4.17.11",
    "mongodb": "^3.1.8",
    "request": "^2.88.0",
    "sha1": "^1.1.1",
    "think-cache": "^1.1.0",
    "think-cache-file": "^1.1.0",
    "think-logger3": "^1.1.1",
    "think-model": "^1.3.0",
    "think-model-mysql": "^1.0.7",
    "think-mongo": "^1.0.9",
    "think-session": "^1.1.1",
    "think-session-file": "^1.1.1",
    "think-view": "^1.0.11",
    "think-view-nunjucks": "^1.0.7",
    "thinkjs": "^3.2.9",
    "wait-until": "^0.0.2",
    "wechat-crypto": "^0.0.2",
    "xml2js": "^0.4.19"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-preset-think-node": "^1.0.3",
    "node-notifier": "^5.3.0",
    "think-watcher": "^3.0.3",
    "think-inspect": "0.0.2",
    "think-babel": "^1.0.6",
    "eslint": "^5.7.0",
    "eslint-config-think": "^1.0.2"
  },`

**Comment by welefen** [comment]
代码中操作 mongo 或者 mysql 么？相关的配置里有没有什么动态修改的配置值。

**Comment by shihuojian** [comment]
有操作mongo

**Comment by welefen** [comment]
是不是 mongo 服务不稳定导致的？直接连下 mongo，然后压测下试试呢

**Comment by songhongjiang** [comment]
这个问题我也遇到了，查询mongo经常报错，尤其是查询语句并发较多的时候
错误如下：
{ TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/home/stsn/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/home/stsn/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5) name: 'TimeoutError' } { request: 
   { method: 'GET',
     url: '/dis/basic/api/vclist?satid=SAT00003',
     header: 
      { accept: 'application/json',
        'user-agent': 'restify/2.6.3 (x64-linux; v8/6.2.414.72; OpenSSL/1.0.2q) node/8.14.0',
        'accept-version': '~1.0',
        date: 'Tue, 29 Jan 2019 07:33:45 GMT',
        host: '39.98.93.230:8360',
        connection: 'keep-alive' } },
  response: 
   { status: 200,
     message: 'OK',
     header: { 'x-powered-by': 'thinkjs-3.2.10' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/dis/basic/api/vclist?satid=SAT00003',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
[2019-01-29T15:33:48.415] [12757] [INFO] - GET /dis/basic/api/vclist?satid=SAT00003 500 3006ms
[2019-01-29T15:33:48.499] [12757] [INFO] - GET /dis/basic/api/inslist?satid=SAT00003 200 3083ms
