### ISSUE TITLE
创建控制器命令行异常， throw new ERR_INVALID_ARG_TYPE('path', 'string', path);

### ISSUE THREAD

**Issue by liuhuanhui** [thinkjs/thinkjs#1273]
thinkjs controller test
```
path.js:39
    throw new ERR_INVALID_ARG_TYPE('path', 'string', path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.normalize (path.js:285:5)
    at Object.isExist (C:\Users\cuizh\AppData\Roaming\npm\node_modules\think-cli\node_modules\think-helper\index.js:376:14)
    at Run.start (C:\Users\cuizh\AppData\Roaming\npm\node_modules\think-cli\lib\run.js:21:12)
    at Object.<anonymous> (C:\Users\cuizh\AppData\Roaming\npm\node_modules\think-cli\bin\thinkjs-controller:92:5)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by lushijie** [comment]
是 *niux 系统么? 先执行一下 thinkjs clean , 如果还有问题请详细描述下 think-cli 版本和 系统信息？

**Comment by liuhuanhui** [comment]
![image](https://user-images.githubusercontent.com/10370625/47827666-1de4f580-ddba-11e8-8ec6-5803f8cf5ca9.png)

**Comment by lushijie** [comment]
你是在 thinkjs 项目根目录执行的么？你的项目是在 C:/Users/cuizh 这个文件夹么

**Comment by liuhuanhui** [comment]
对的
