### ISSUE TITLE
添加mongodb配置后，提示config.handle must be a function

### ISSUE THREAD

**Issue by gsxhnd** [thinkjs/thinkjs#1277]
## DESC
model层即使不添加内容，调用restful api 时也会报错
### ENV

OS Platform:windows 10

Node.js Version:v8.11.1

ThinkJS Version:3.2.9

think-mongo: 1.0.9

### code

```js
// adapter.js
exports.model = {
  type: 'mongo', 
  common: { 
    logConnect: true, 
    logger: msg => think.logger.info(msg)
  },
  mongo: {
    host: '127.0.0.1',
    port: 27017,
    user: '',
    password: '',
    database: 'test', // 数据库名称
    options: {
      replicaSet: 'mgset-3074013',
      authSource: 'admin'
    }
  }
}

```

### error message

```
//  error message 
{ AssertionError [ERR_ASSERTION]: config.handle must be a function
    at new Model (D:\Projects\test\explorer-api\node_modules\think-model\lib\model.js:25:5)
    at model (D:\Projects\test\explorer-api\node_modules\think-model\index.js:31:22)
    at Object.model (D:\Projects\test\explorer-api\node_modules\think-model\index.js:67:26)
    at module.exports.model (D:\Projects\test\explorer-api\node_modules\think-model\index.js:61:25)
    at new module.exports (D:\Projects\test\explorer-api\src\controller\rest.js:13:31)
    at new module.exports (D:\Projects\test\explorer-api\src\controller\api\test\getAccount.js:4:18)
    at D:\Projects\test\explorer-api\node_modules\think-controller\index.js:38:22
    at dispatch (D:\Projects\test\explorer-api\node_modules\koa-compose\index.js:42:32)
    at promise.then.then.then.data (D:\Projects\test\explorer-api\node_modules\think-logic\index.js:79:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' } { request: 
   { method: 'GET',
     url: '/api/v1/test/getAccount',
     header: 
      { 'cache-control': 'no-cache',
        'postman-token': '5eff0de4-a78b-4e42-b583-3f6c4f6ee145',
        'user-agent': 'PostmanRuntime/7.3.0',
        accept: '*/*',
        host: '127.0.0.1:8080',
        'accept-encoding': 'gzip, deflate',
        connection: 'keep-alive' } },
  response: 
   { status: 404,
     message: 'Not Found',
     header: { 'x-powered-by': 'thinkjs-3.2.9' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/api/v1/chain/getAccount',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
[2018-11-01T16:48:31.236] [18984] [INFO] - GET /api/v1/test/getAccount 500 38ms
```

**Comment by welefen** [comment]
mongo 有些特殊，使用起来有些差异，具体见文档：https://thinkjs.org/zh-cn/doc/3.0/mongo.html

**Comment by gsxhnd** [comment]
> mongo 有些特殊，使用起来有些差异，具体见文档：https://thinkjs.org/zh-cn/doc/3.0/mongo.html

已经是照着文档配置，然后用原生的库是可以插入数据。

```
// test.js
const MongoClient = require('mongodb').MongoClient;
const assert = require('assert');

// Connection URL
const url = 'mongodb://192.168.1.111:27017';

// Database Name
const dbName = 'test';

const insertDocuments = function(db, callback) {
    // Get the documents collection
    const collection = db.collection('documents');
    // Insert some documents
    collection.insertMany([
      {a : 1}, {a : 2}, {a : 3}
    ], function(err, result) {
      assert.equal(err, null);
      assert.equal(3, result.result.n);
      assert.equal(3, result.ops.length);
      console.log("Inserted 3 documents into the collection");
      callback(result);
    });
  }

// Use connect method to connect to the server
MongoClient.connect(url, function(err, client) {
  assert.equal(null, err);
  console.log("Connected successfully to server");

  const db = client.db(dbName);

  insertDocuments(db, function() {
    client.close();
  });
});
```

**Comment by gsxhnd** [comment]
> > mongo 有些特殊，使用起来有些差异，具体见文档：https://thinkjs.org/zh-cn/doc/3.0/mongo.html
> 
> 已经是照着文档配置，然后用原生的库是可以插入数据。
> 
> ```
> // test.js
> const MongoClient = require('mongodb').MongoClient;
> const assert = require('assert');
> 
> // Connection URL
> const url = 'mongodb://192.168.1.111:27017';
> 
> // Database Name
> const dbName = 'test';
> 
> const insertDocuments = function(db, callback) {
>     // Get the documents collection
>     const collection = db.collection('documents');
>     // Insert some documents
>     collection.insertMany([
>       {a : 1}, {a : 2}, {a : 3}
>     ], function(err, result) {
>       assert.equal(err, null);
>       assert.equal(3, result.result.n);
>       assert.equal(3, result.ops.length);
>       console.log("Inserted 3 documents into the collection");
>       callback(result);
>     });
>   }
> 
> // Use connect method to connect to the server
> MongoClient.connect(url, function(err, client) {
>   assert.equal(null, err);
>   console.log("Connected successfully to server");
> 
>   const db = client.db(dbName);
> 
>   insertDocuments(db, function() {
>     client.close();
>   });
> });
> ```

问题解决了，mongo配置需要添加`handle: mongo,`文档处漏了这个选项。
