### ISSUE TITLE
think.cache获取redis hash缓存报错

### ISSUE THREAD

**Issue by RonnieDuck** [thinkjs/thinkjs#1302]
## DESC
缓存以redis hash的形式存储，think.cache方法是否不能读取这种数据形式？
think.cache支持哪几种redis的数据形式？
### ENV

OS Platform: OSX

Node.js Version: 10.13.0

ThinkJS Version: 2.2

### code

```js
//cache.js
'use strict';

export default {
  type: 'redis',
  adapter: {
    redis: {
      prefix: ''
    }
  }
};
//redis.js
export default {
    host: 'xx.xx.xx.xx',
    port: 6379,
    password: '1234567',
    timeout: 5,
    log_connect: true
};
//global.js
think.cache('key name').then(result=>console.log(result));
```

### error message

```
[2018-12-03 14:05:47] [Error] Error: WRONGTYPE Operation against a key holding the wrong kind of value
    at JavascriptReplyParser._parseResult (/Users/ronnieduck/Documents/Company/taobaoke_data_processor/node_modules/redis/lib/parsers/javascript.js:37:16)
    at JavascriptReplyParser.execute (/Users/ronnieduck/Documents/Company/taobaoke_data_processor/node_modules/redis/lib/parsers/javascript.js:113:38)
    at Socket.<anonymous> (/Users/ronnieduck/Documents/Company/taobaoke_data_processor/node_modules/redis/index.js:117:27)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
```

### more description

// your detail description

**Comment by welefen** [comment]
cache 时会将数据序列化（通过 JSON.stringify），所以只能缓存 stringify 的值

**Comment by RonnieDuck** [comment]
@welefen 所以redis里面非string类型的获取就会报错吗？
