### ISSUE TITLE
希望mysql出错的异常会输出错误的语句

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#1317]
查看日志发现一大堆这样的异常，奇怪的是开发环境下没有出现这个问题，而在生产环境下每过几天就会出现一堆这样的错误。
但是光靠这个信息我只知道是where中某个条件值为NaN导致错误，但根本没办法排查是哪个地方导致的这个错误，毕竟用where的太多，也不知道是哪个字段设置为了NaN。
最好的办法是，抛出异常的时候把具体的语句也包含在抛出的信息里面，这样就能很快定位是哪里的问题了

```
{ Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (/www/nodejs/xxx/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/www/nodejs/xxx/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/www/nodejs/xxx/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/www/nodejs/xxx/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/www/nodejs/xxx/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/www/nodejs/xxx/node_modules/mysql/lib/Connection.js:103:28)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (/www/nodejs/xxx/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (/www/nodejs/xxx/node_modules/mysql/lib/Connection.js:208:25)
    at Promise (/www/nodejs/xxx/node_modules/think-helper/index.js:83:10)
    at new Promise (<anonymous>)
    at args (/www/nodejs/xxx/node_modules/think-helper/index.js:82:12)
    at ThinkMysql.[think-mysql-query] (/www/nodejs/xxx/node_modules/think-mysql/index.js:151:12)
    at getConnection.then.connection (/www/nodejs/xxx/node_modules/think-mysql/index.js:209:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0 }
```

**Comment by welefen** [comment]
暂时可以把 adapter.js 里的 logSql 配置打开，后面我们改进下，报错的时候在 message 里把 SQL 语句带上

**Comment by welefen** [comment]
think-mysql@1.3.0
