### ISSUE TITLE
提示__after方法名在koa-compose中不建议并在后续版本会废弃

### ISSUE THREAD

**Issue by orchie** [thinkjs/thinkjs#1323]
## DESC
今天刚用tj感觉很棒 初始化start以后有一行提示  
logic deprecated logic's __after method is deprecated, it will be discarded in the next version  at node_modules\koa-compose\index.js:42:32  
提示__after方法名在koa-compose中不建议并在后续版本会废弃
这样以后会造成影响或什么隐患吗？
### ENV

OS Platform:
win10x64
Node.js Version:
11.4
ThinkJS Version:
 3.2.1
### code

```js
npm start
```

### error message

```
[2019-01-09T16:19:13.982] [30368] [INFO] - Server running at http://127.0.0.1:8360
[2019-01-09T16:19:13.987] [30368] [INFO] - ThinkJS version: 3.2.10
[2019-01-09T16:19:13.987] [30368] [INFO] - Environment: development
[2019-01-09T16:19:13.987] [30368] [INFO] - Workers: 1
[2019-01-09T16:19:25.646] [27552] [INFO] - GET /favicon.ico 404 5ms
Wed, 09 Jan 2019 08:19:31 GMT logic deprecated logic's __after method is deprecated, it will be discarded in the next version  at node_modules\koa-compose\index.js:42:32
[2019-01-09T16:19:31.431] [27552] [INFO] - GET / 200 9ms
```

### more description

// your detail description

**Comment by lizheming** [comment]
自己的代码中不使用 `__after()` 即可，其它的无影响。
