### ISSUE TITLE
thinkjs 3.2.10 在unbuntu上新建项目启动报错

### ISSUE THREAD

**Issue by DickyNet** [thinkjs/thinkjs#1352]
## DESC
thinkjs 3.2.10 在unbuntu上新建项目启动报错
### ENV

OS Platform: unbuntu

Node.js Version: node.js 6.10.0

ThinkJS Version:  3.2.10

### code
用 thinkjs new demo 命令生成的项目无法运行报以下错误
```js
// your code here
```

### error message

```
// your error message here
```
cbnbuntu@web-130-43:/var/www/demo$ npm start

> demo@1.0.0 start /var/www/demo
> node development.js

[2019-03-26T17:59:33.704] [20913] [INFO] - Server running at http://127.0.0.1:8360
[2019-03-26T17:59:33.708] [20913] [INFO] - ThinkJS version: 3.2.10
[2019-03-26T17:59:33.709] [20913] [INFO] - Environment: development
[2019-03-26T17:59:33.709] [20913] [INFO] - Workers: 1
/var/www/demo/node_modules/think-trace/lib/tracer.js:55
  async getTemplateContent() {
        ^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/demo/node_modules/think-trace/lib/index.js:4:16)
    at Module._compile (module.js:570:32)

### more description

// your detail description

**Comment by luckyscript** [comment]
将node.js版本升到7以上

**Comment by DickyNet** [comment]
谢谢，果然是版本问题 建议新建的demo项目里的package.json中依赖版本更改为  "engines": {
    "node": ">=7.0.0"
  }

**Comment by makeco** [comment]
`thinkjs new projectName` 创建的项目默认关闭了babel，为了支持async/await，我把最小支持版本改为当前LTS(v8.15.1)了。如果再次用thinkjs new 创建项目发现 engines 中的版本没有改，请把 `~/.think-templates` 删掉。
