### ISSUE TITLE
think-mysql 升级到 1.4.0 线上经常卡死

### ISSUE THREAD

**Issue by arterli** [thinkjs/thinkjs#1372]
## DESC
think-mysql 升级到 1.4.0 线上经常卡死，

### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here

```

### error message

```
// your error message here
[2019-05-08T00:29:04.997] [ERROR] default - unhandledRejection, times: 1, pid: 31765
[2019-05-08T00:29:04.997] [ERROR] default - Error: cannot create more connection in transation, use db() to reuse connection!
    at ThinkMysql.getConnection (/www/wwwroot/yyfzx/node_modules/think-mysql/index.js:78:29)
    at debounceInstance.debounce (/www/wwwroot/yyfzx/node_modules/think-mysql/index.js:225:21)
    at Promise.resolve.then (/www/wwwroot/yyfzx/node_modules/think-debounce/index.js:19:16)
[2019-05-08T00:29:04.997] [ERROR] default - Error: cannot create more connection in transation, use db() to reuse connection!
    at ThinkMysql.getConnection (/www/wwwroot/yyfzx/node_modules/think-mysql/index.js:78:29)
    at debounceInstance.debounce (/www/wwwroot/yyfzx/node_modules/think-mysql/index.js:225:21)
    at Promise.resolve.then (/www/wwwroot/yyfzx/node_modules/think-debounce/index.js:19:16)
[2019-05-08T00:34:45.043] [ERROR] default - unhandledRejection, times: 2, pid: 31765
[2019-05-08T00:34:45.043] [ERROR] default - Error: cannot create more connection in transation, use db() to reuse connection!
    at ThinkMysql.getConnection (/www/wwwroot/yyfzx/node_modules/think-mysql/index.js:78:29)
    at debounceInstance.debounce (/www/wwwroot/yyfzx/node_modules/think-mysql/index.js:225:21)
    at Promise.resolve.then (/www/wwwroot/yyfzx/node_modules/think-debounce/index.js:19:16)
[2019-05-08T00:34:45.043] [ERROR] default - Error: cannot create more connection in transation, use db() to reuse connection!
    at ThinkMysql.getConnection (/www/wwwroot/yyfzx/node_modules/think-mysql/index.js:78:29)
    at debounceInstance.debounce (/www/wwwroot/yyfzx/node_modules/think-mysql/index.js:225:21)
    at Promise.resolve.then (/www/wwwroot/yyfzx/node_modules/think-debounce/index.js:19:16)
```

### more description

// your detail description

**Comment by luckyscript** [comment]
可以贴一下你事务相关的代码么？事务里面需要用db()来复用连接。https://github.com/thinkjs/thinkjs/issues/1334

**Comment by arterli** [comment]
都检查了几十遍了，而且是相同的业务代码，以前没有任何问题，自从升级到think-mysql 1.4.0,就开始出现。绝对不是db()复用的问题

**Comment by arterli** [comment]
而且每天都会卡住。都升级了些啥啊。

**Comment by arterli** [comment]
有部分客户还没又升级的，用的是 think-mysql 1.2.5 出现任何问题，升级的，每天都卡住。相同的代码。

**Comment by arterli** [comment]
哥们我怎么退回去，并且指定用1.2..5,这不是坑人吗，几百客户，的收银台，天天卡住。都疯了。

**Comment by lizheming** [comment]
MySQL 的配置提供下吧，把关键信息过滤一下。

**Comment by arterli** [comment]
云数据库的配置？

**Comment by lizheming** [comment]
@arterli 想看一下你有没有配线程池相关的配置。你如果确认 `think-mysql@1.2.5` 这个版本没有问题的话，可以上机器强制 `npm install think-mysql@1.2.5` 然后重启下服务器就可以了。我后续再看看这块的逻辑。

**Comment by arterli** [comment]
@lizheming 好，因为是自动安装，自动安装会用安装最新版的依赖，所以新安装的1.4.0的，都出问题了，上百个呢，我先一个一个恢复到 1.2.5

**Comment by lizheming** [comment]
@arterli 已经安装了的话没太多办法，写个批量脚本执行下吧。我们尽快看下这个问题，具体QQ沟通。

**Comment by bravecat** [comment]
一个事务未完成时，开启另一个事务会报错。`cannot create more connection in transation, use db() to reuse connection!` 。例如用下面代码，在5秒内请求两次就会报错：

```js
async indexAction() {
  const model = think.model('user')
  await model.transaction(async () => {
    /** 模拟事务需要5秒执行完成 */
    await new Promise(res => setTimeout(res, 5000))
  })
  return this.success('hello')
}
```

**Comment by arterli** [comment]
https://thinkjs.org/doc/3.0/relation_model.html#toc-e30
参考下这里。事物里面嵌套model，要处理下。



------------------ 原始邮件 ------------------
发件人: "CaiZhiYong"<notifications@github.com>; 
发送时间: 2019年5月31日(星期五) 下午5:35
收件人: "thinkjs/thinkjs"<thinkjs@noreply.github.com>; 
抄送: "阿特"<arterli@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [thinkjs/thinkjs] think-mysql 升级到 1.4.0 线上经常卡死 (#1372)




一个事务未完成时，开启另一个事务会报错。cannot create more connection in transation, use db() to reuse connection! 。例如用下面代码，在5秒内请求两次就会报错：
 async indexAction() {   const model = think.model('user')   await model.transaction(async () => {     /** 模拟事务需要5秒执行完成 */     await new Promise(res => setTimeout(res, 5000))   })   return this.success('hello') }
 
&mdash;

**Comment by bravecat** [comment]
@arterli 你好，我这个例子怎么处理好呢？里面没有用到嵌套model的。

**Comment by lizheming** [comment]
@bravecat 请提供一个最小可复现的环境，我拿着你之前给的代码在本地试了是 OK 的，具体见截图。
![image](https://user-images.githubusercontent.com/424491/58703092-21853d00-83da-11e9-8378-99f269c8f1bc.png)
![image](https://user-images.githubusercontent.com/424491/58703096-2813b480-83da-11e9-892e-dfe9662a1e40.png)
![image](https://user-images.githubusercontent.com/424491/58703112-2f3ac280-83da-11e9-8e38-2208cac699ca.png)

**Comment by bravecat** [comment]
@lizheming 你好，我测试下最新的`think-mysql 1.4.2`没有这个问题，`1.4.0`版本有，在`package.json` 指定安装`"think-mysql": "1.4.0"`即可出现。

**Comment by lizheming** [comment]
@bravecat 新版本没有那就忽略吧
