### ISSUE TITLE
自定义的redis连接报错

### ISSUE THREAD

**Issue by RonnieDuck** [thinkjs/thinkjs#1383]
## DESC
在Service的方法里面创建redis连接，然后再使用think.cache读取相关缓存，第二次调用的时候报错。
个人认为是service里面和think定义的redis连接产生了冲突？
ps: 使用redis缓存时，think的adapter封装好了只有get和set等方法，怎么样可以拿到think里面可以发送redis命令的redis连接而又不影响cache的adapter呢？
### ENV

OS Platform: OSX

Node.js Version: 10.13

ThinkJS Version: 2.2

### code

```js
// service/util.js
'use strict';

import redis from 'redis';

export default class extends think.service.base {
  init(...args) {
    super.init(...args);
    this.redisConfig = think.config('redis');
  }
  async redisIndistinctKey(indistinctKey) {
    try {
      const client = redis.createClient(this.redisConfig);
      const keys = await new Promise((resolve, reject) => {
        client.on('error', err => reject(err));
        client.on('ready', () => {
          client.keys(indistinctKey, (err, replies) => {
            err ? reject(err) : resolve(replies);
          });
        });
        client.quit();
      });
      return keys;
    } catch (err) {
      throw err;
    }
  }
}

// service/cache.js
'use strict';

export default class extends think.service.base {
  init(...args) {
    super.init(...args);
  }
  async activeDomain(lineId, type, random = true) {
    try {
      const domainKeys = await global.utilService.redisIndistinctKey(`line${lineId}_${type}_domain#*`);
      console.log(domainKeys);
      if (domainKeys.length === 0) {
        const domains = await think.model('domain', undefined, 'common').field('id,domain').where({ line_id: lineId, type: type, status: 1 }).order('id ASC').select();
        if (domains.length === 0) {
          throw new Error('NOT_EXIST_DOMAIN');
        }
        const promises = [];
        for (let i = 0; i < domains.length; i++) {
          domainKeys.push(`line${lineId}_${type}_domain#${domains[i].id}`);
          promises.push(think.cache(`line${lineId}_${type}_domain#${domains[i].id}`, domains[i].domain));
        }
        await Promise.all(promises);
        const index = random ? parseInt(Math.random() * domains.length) : 0;
        return domains[index].domain;
      } else {
        const index = random ? parseInt(Math.random() * domainKeys.length) : 0;
        const domain = await think.cache(domainKeys[index]);
        return domain;
      }
    } catch (err) {
      throw err;
    }
  }
}
```

### error message

```
[2019-06-05 15:31:33] [Error] AbortError: Stream connection ended and command aborted. It might have been processed.
    at RedisClient.flush_and_error (/Users/ronnieduck/Documents/Company/lb_management/node_modules/redis/index.js:362:23)
    at RedisClient.connection_gone (/Users/ronnieduck/Documents/Company/lb_management/node_modules/redis/index.js:597:14)
    at RedisClient.on_error (/Users/ronnieduck/Documents/Company/lb_management/node_modules/redis/index.js:410:10)
    at Socket.<anonymous> (/Users/ronnieduck/Documents/Company/lb_management/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### more description
我的出发点是想要做redis的key模糊查询
// your detail description

**Comment by RonnieDuck** [comment]
@welefen 求助

**Comment by lizheming** [comment]
https://stackoverflow.com/questions/39424971/connection-ended-and-command-aborted-in-a-script

看这个问题，应该是你的 `client.quit()` 调用地方有问题吧
```js
client.on('ready', () => {
  client.keys(indistinctKey, (err, replies) => {
    client.quit();
    err ? reject(err) : resolve(replies);
  });
});
```

**Comment by RonnieDuck** [comment]
@lizheming 我也试过在回调里面调用client.quit()，不过效果相同还是会报错

**Comment by lizheming** [comment]
那你把 cache 操作去了是否就不报错了？

**Comment by RonnieDuck** [comment]
我刚刚尝试用内网方式连接redis就不报错了，谢谢

**Comment by lizheming** [comment]
好的
