### ISSUE TITLE
同时配置mysql、mongodb，链接mongodb异常

### ISSUE THREAD

**Issue by renxiaomeng** [thinkjs/thinkjs#1397]
OS Platform: window 10

Node.js Version: 10.14.2

ThinkJS Version: 3.2.10

### code
extend.js
```js
const view = require('think-view');
const model = require('think-model');
const cache = require('think-cache');
const session = require('think-session');
const mongo = require('think-mongo');

module.exports = [
  view, // make application support view
  model(think.app),
  mongo(think.app),
  cache,
  session
];
```
adapter.js
```js
exports.model = {
  type: 'mysql',
  common: {
    logConnect: isDev,
    logSql: isDev,
    logger: msg => think.logger.info(msg)
  },
  mysql: {
    handle: mysql,
    database: 'think-test',
    prefix: 'think_',
    encoding: 'utf8',
    host: '127.0.0.1',
    port: '3306',
    user: 'root',
    password: 'root',
    dateStrings: true
  },
  mongo: {
    handle: mongo,
    host: '127.0.0.1',
    port: '27017',
    user: 'think',
    password: 'think-123',
    database: 'think-test'
  }
};
```

controller\user.js
```js
const Base = require('./base.js');
module.exports = class extends Base {
  async indexAction() {
    const model = this.mongo('user');
    const users = await model.select();
    return this.success(users, '获取成功');
  }
};
```

### error message

```
[2019-07-04T16:15:15.771] [73572] [INFO] - mongodb://root:root@127.0.0.1:3306/think-test
[2019-07-04T16:15:15.796] [73572] [INFO] - mongodb://root:root@127.0.0.1:3306/think-test
[2019-07-04T16:15:15.811] [73572] [ERROR] - uncaughtException, times: 1, pid: 73572
[2019-07-04T16:15:15.811] [73572] [ERROR] - TypeError: Cannot read property 'socketTimeout' of null
    at Connection.messageHandler (E:\node\thinkjs\helloworld\node_modules\mongodb-core\lib\connection\pool.js:410:17)
    at Socket.<anonymous> (E:\node\thinkjs\helloworld\node_modules\mongodb-core\lib\connection\connection.js:363:20)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:448) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
```

### more description
mongodb://root:root@127.0.0.1:3306/think-test
mongodb请求地址居然是 mysql和mongodb 配置的合体
是在不晓得是我哪里写错了还是真的有BUG

**Comment by lizheming** [comment]
`this.mongo('user', 'mongo')` 试试。
