### ISSUE TITLE
动态添加自定义路由path-to-regexp报错，但添加的路由规则能用

### ISSUE THREAD

**Issue by GitProQ** [thinkjs/thinkjs#1409]
### ENV

OS Platform: Win 10 版本1803 内部版本17134.407

Node.js Version: v10.15.3

ThinkJS Version: 3.2.10

### code

```js
work.js：
// invoked in worker
think.beforeStartServer(async() => {
  // 将所有的自定义路由保存在字段为 router 的数据上
  const routers = [ 
    [ '/about/:pathname', 'show/index' ],
    [ '/blog/:pathname', 'blog/index' ],
    [ '/wallpaper', 'image/index' ],
    [ '/wallpaper/:pathname', 'image/index' ],
    [ '/anime/:pathname', 'bangumi/index' ],
    [ '/webapp/:pathname', 'webapp/index' ],
    [ '/video/:pathname', 'video/index' ] 
 ];
  console.log(routers);
  // 触发 routerChange 事件，将新的自定义路由设置到 think.app.routers 对象上
  // routers 格式和自定义路由格式相同，二维数组
  think.app.emit('routerChange', routers);
});
```

### error message

```
TypeError: Cannot read property 'length' of undefined
    at parse (G:\App\nodejs\demo\node_modules\think-router\node_modules\path-to-regexp\index.js:91:19)
    at stringToRegexp (G:\App\nodejs\demo\node_modules\think-router\node_modules\path-to-regexp\index.js:322:25)
    at pathToRegexp (G:\App\nodejs\demo\node_modules\think-router\node_modules\path-to-regexp\index.js:425:10)
    at formatRule (G:\App\nodejs\demo\node_modules\think-router\index.js:27:17)
    at routers.map.item (G:\App\nodejs\demo\node_modules\think-router\index.js:58:16)
    at Array.map (<anonymous>)
    at formatRouters (G:\App\nodejs\demo\node_modules\think-router\index.js:50:20)
    at Application.app.once (G:\App\nodejs\demo\node_modules\think-router\index.js:92:19)
    at Object.onceWrapper (events.js:277:13)
    at Application.emit (events.js:189:13)
```

### more description

// your detail description 
routers那就直接粘贴 从数据库得到的栏目数据，再转成和router.js一样的二维数组，怎么查询转换就不放上去了， 然后提示pathToRegexp里面的parse方法 str 为 undefined，升级think-router到1.3.3也无法解决

**Comment by lizheming** [comment]
你好，文档这块应该有点问题，你改成使用 `think.app.on('appReady', async() => {})` 事件去做应该就可以了。

**Comment by GitProQ** [comment]
> 你好，文档这块应该有点问题，你改成使用 `think.app.on('appReady', async() => {})` 事件去做应该就可以了。

非常感谢 问题解决了

**Comment by lizheming** [comment]
文档中提供的动态路由方式是在 `beforeStartServer` 事件中执行 https://thinkjs.org/zh-cn/doc/3.0/router.html#toc-3ad 
在 think-router 中同时对 `routerChange` 和 `appReady` 两个事件进行了监听，前者是用来处理动态修改路由，而后者 `appReady` 事件监听是用来处理用户默认在 `router.js` 中配置的自定义路由。也就是说在 `beforeStartServer` 事件做 `routerChange` 的出发的话会同时触发两次 `formatRouters` 方法，而在第一期触发完毕后 `app.routers` 已经是解析后的标准化 router 对象了，所以在下一次再执行的时候数据格式不正确就报错了。

根据原因解决办法有两种，第一种则是像上文所说规避 `appReady` 事件，尽量在 `appReady` 之后执行动态路由设置即可。还有一种修改方式则是在 `formatRouters` 方法中做兼容，判断如果已经是标准化的 `routers` 对象的话就直接返回即可。

**Comment by lushijie** [comment]
@GitProQ think-router@1.3.4 fixed routerChange error .
