### ISSUE TITLE
【BUG反馈】think-model version：1.3.3 

### ISSUE THREAD

**Issue by shasharoman** [thinkjs/thinkjs#1428]
postgresql，think-model由1.3.2升级到1.3.3，导致应用运行出现SQL语法错误。

1.3.3报错如下：
``` text
SQL: SELECT COUNT(`d`.field_x) AS think_count FROM table_x AS d INNER JOIN table_y AS "c" ON d.field_y = "c".field_y WHERE ( field_z = E'001' ) LIMIT 1, Time: 32ms

  error: syntax error at or near "."
      at Connection.parseE (/root/ws/apollo/node_modules/pg/lib/connection.js:604:11)
      at Connection.parseMessage (/root/ws/apollo/node_modules/pg/lib/connection.js:401:19)
      at Socket.<anonymous> (/root/ws/apollo/node_modules/pg/lib/connection.js:121:22)
      at Socket.emit (events.js:198:13)
      at addChunk (_stream_readable.js:288:12)
      at readableAddChunk (_stream_readable.js:269:11)
      at Socket.Readable.push (_stream_readable.js:224:10)
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

1.3.2 will be ok：
``` text
SQL: SELECT COUNT(d.field_x) AS think_count FROM table_x AS d INNER JOIN table_y AS "c" ON d.field_y = "c".field_y WHERE ( field_z = E'001' ) LIMIT 1, Time: 32ms
```

初步判断，是因为1.3.3在这个[COMMIT](https://github.com/thinkjs/think-model/commit/468df843ba0b56bf3dd38941839e243ff2875312)中为count方法的table包了一层"``"，由此引发了悲剧。

**Comment by lizheming** [comment]
唔？所以 postgresql 不支持反引号包裹么？

**Comment by welefen** [comment]
多谢反馈，think-model@1.3.5 已经修复
