### ISSUE TITLE
多进程里的master进程不能使用Service?

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#1520]
场景是这样的，程序使用了小程序的API，所以要获取AccessToken，如果各个worker各自获取，就会导致AccessToken重复失效的问题（因为刷新AccessToken会导致旧的AccessToken失效），所以就要做一个中控服务，统一获取和缓存AccessToken，我想做到master进程里，然后各个worker使用think.messenger.consume来获取AccessToken，由master进程统一刷新AccessToken。
但是实际发现master进程无法使用Service，使用think.service出现下面的异常：
```
TypeError: Cannot read property 'length' of undefined
    at Object.think.service (E:\data\Project\xxx\server\node_modules\thinkjs\lib\think.js:68:25)
    at Object.<anonymous> (E:\data\Project\xxx\server\src\common\bootstrap\master.js:5:28)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at loadBootstrap (E:\data\Project\xxx\server\node_modules\think-loader\loader\bootstrap.js:18:12)
    at Loader.loadBootstrap (E:\data\Project\xxx\server\node_modules\think-loader\index.js:42:12)
```

PS：
之前一个项目使用的redis来缓存AccessToken和过期时间，然后所有worker共用redis里的AccessToken，但并没有从根本上解决多个进程可能同时刷新的问题。比如高并发下，多个进程同时获取AccessToken和过期时间，发现过期了，就同时刷新AccessToken，结果导致出现一瞬间刷新多次的问题。

如果master不能使用service是thinkjs的限制，那就只能单独做个程序来统一管理和发放AccessToken了。

又或许我应该把微信小程序的接口单独封装成一个普通的JS类，然后在master进程里使用js自带的new来实例化，而不是service？

**Comment by lizheming** [comment]
你的这个问题本质和多进程无关，本质是如何做高并发下的锁的问题。ThinkJS 中 Master 只用来做请求分发，如果 Master 承载请求逻辑的话，在那段时间内的请求都会无法响应！

针对你的情况有几个思路可以选择：

1. 启一个定时任务单独去刷新 Token，所有接口都直接取 Token 即可
2. token 和更新状态可以使用 `think.messenger.broadcast` 进程间通信广播告知所有的 Worker https://thinkjs.org/zh-cn/doc/3.0/multi_process.html#toc-137
3. 使用 Redis 外部存储来进行锁状态判断

本质上这三个解决方法是无锁，内存锁，外部存储锁的解决思路。另外你的问题可参考该篇文章的讨论：https://www.v2ex.com/t/308349

**Comment by welefen** [comment]
直接弄个定时任务更新 token 然后存到 redis，用户请求的时候直接获取就好了。

不要用多进程模型来处理，万一后面要加多个机器/多个机房，不又杯具了么

**Comment by KuoKongQingYun** [comment]
谢谢，
1.没使用计划任务的原因是不想单独弄个控制器来处理接口服务的，会增加耦合。
2.其实也没有保证不会出现多个进程同时刷新。
3.目前考虑这个，
