### ISSUE TITLE
无法在Object原型上添加方法

### ISSUE THREAD

**Issue by yh4922** [thinkjs/thinkjs#1705]
无法在`Object.prototype`原型上添加方法
```javascript
Object.prototype.testAAA = function () {
  console.log(this)
}
```

报错
```base
[2022-06-30T10:59:54.081] [17860] [INFO] - Server running at http://127.0.0.1:8360
[2022-06-30T10:59:54.083] [17860] [INFO] - ThinkJS version: 3.2.14
[2022-06-30T10:59:54.083] [17860] [INFO] - Environment: development
[2022-06-30T10:59:54.083] [17860] [INFO] - Workers: 1
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md node_modules/thinkjs/lib/loader.js:57:17
(node:17867) [MONGODB DRIVER] Warning: the options [testAAA] is not supported
[2022-06-30T10:59:54.699] [17867] [ERROR] - unhandledRejection, times: 1, pid: 17867
[2022-06-30T10:59:54.699] [17867] [ERROR] - TypeError: s2.virtuals[virtual].clone is not a function
    at merge (/root/nodejs/ccbp_server/node_modules/think-mongoose/node_modules/mongoose/lib/helpers/schema/merge.js:23:49)
    at Schema.add (/root/nodejs/ccbp_server/node_modules/think-mongoose/node_modules/mongoose/lib/schema.js:460:5)
    at new Schema (/root/nodejs/ccbp_server/node_modules/think-mongoose/node_modules/mongoose/lib/schema.js:132:10)
    at new Mongoose (/root/nodejs/ccbp_server/node_modules/think-mongoose/lib/model.js:28:16)
    at new module.exports (/root/nodejs/ccbp_server/src/model/cbi_admin.js:8:5)
    at model (/root/nodejs/ccbp_server/node_modules/think-mongoose/index.js:10:22)
    at Object.injectModel [as mongoose] (/root/nodejs/ccbp_server/node_modules/think-mongoose/index.js:19:12)
    at Messenger.module.exports (/root/nodejs/ccbp_server/src/bootstrap/initialize.js:3:31)
    at Messenger.emit (events.js:314:20)
    at process.<anonymous> (/root/nodejs/ccbp_server/node_modules/think-cluster/lib/messenger.js:82:16)
    at process.emit (events.js:326:22)
    at process.emit (/root/nodejs/ccbp_server/node_modules/source-map-support/source-map-support.js:439:21)
    at emit (internal/child_process.js:877:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[2022-06-30T10:59:54.702] [17867] [ERROR] - TypeError: s2.virtuals[virtual].clone is not a function
    at merge (/root/nodejs/ccbp_server/node_modules/think-mongoose/node_modules/mongoose/lib/helpers/schema/merge.js:23:49)
    at Schema.add (/root/nodejs/ccbp_server/node_modules/think-mongoose/node_modules/mongoose/lib/schema.js:460:5)
    at new Schema (/root/nodejs/ccbp_server/node_modules/think-mongoose/node_modules/mongoose/lib/schema.js:132:10)
    at new Mongoose (/root/nodejs/ccbp_server/node_modules/think-mongoose/lib/model.js:28:16)
    at new module.exports (/root/nodejs/ccbp_server/src/model/cbi_admin.js:8:5)
    at model (/root/nodejs/ccbp_server/node_modules/think-mongoose/index.js:10:22)
    at Object.injectModel [as mongoose] (/root/nodejs/ccbp_server/node_modules/think-mongoose/index.js:19:12)
    at Messenger.module.exports (/root/nodejs/ccbp_server/src/bootstrap/initialize.js:3:31)
    at Messenger.emit (events.js:314:20)
    at process.<anonymous> (/root/nodejs/ccbp_server/node_modules/think-cluster/lib/messenger.js:82:16)
    at process.emit (events.js:326:22)
    at process.emit (/root/nodejs/ccbp_server/node_modules/source-map-support/source-map-support.js:439:21)
    at emit (internal/child_process.js:877:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

好像是mongodb影响到了

**Comment by lizheming** [comment]
在 `bootstrap/master.js` 和 `bootstrap/worker.js` 里都要定义一遍。代码执行具体是在 woker 进程里执行的。

**Comment by yh4922** [comment]
![image](https://user-images.githubusercontent.com/18353610/176610198-b9b875d9-1145-45d1-8ceb-d3ae41456b6e.png)
都定义一边好像也不行

**Comment by lizheming** [comment]
本地实测过没有问题，如果有问题请自己自查一下。这个已经和 ThinkJS 无关了，属于基本的 JS 语法问题。
另外多说一句，公共方法不建议修改原型去定义，建议直接使用 ThinkJS 的 `extend` 去挂载，具体见文档 https://thinkjs.org/zh-cn/doc/3.0/extend.html
