### ISSUE TITLE
使用2.2.16创建的 ts 版本项目编译报错

### ISSUE THREAD

**Issue by del1214** [thinkjs/thinkjs#567]
## DESC
使用2.2.16创建的 ts 版本项目编译报错
项目下所有 ts 文件都会编译报错内容如下:

`[2017-02-16 15:41:21] [COMPILE] compile file home/model/index.ts error
[2017-02-16 15:41:21] [Error] TypeError: Cannot read property 'getLineAndCharacterOfPosition' of undefined
    at _class.compileByTypeScript (/Users/del1214/Test/aaa_jstest/node_modules/thinkjs/lib/util/watch_compile.js:157:56)
    at _class.compileFile (/Users/del1214/Test/aaa_jstest/node_modules/thinkjs/lib/util/watch_compile.js:99:14)
    at /Users/del1214/Test/aaa_jstest/node_modules/thinkjs/lib/util/watch_compile.js:321:26
    at Array.forEach (native)
    at _class.compile (/Users/del1214/Test/aaa_jstest/node_modules/thinkjs/lib/util/watch_compile.js:299:11)
    at _class.run (/Users/del1214/Test/aaa_jstest/node_modules/thinkjs/lib/util/watch_compile.js:355:10)
    at _class.compile (/Users/del1214/Test/aaa_jstest/node_modules/thinkjs/lib/index.js:522:14)
    at Object.<anonymous> (/Users/del1214/Test/aaa_jstest/www/development.js:15:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)`

## ENV

Platform:

Node.js Version:
6.9.5
ThinkJS Version:
2.2.16

**Comment by welefen** [comment]
Please change TypeScript version to 2.0.3, then install it.

**Comment by del1214** [comment]
感谢回复!不过问题依旧,我在同事的机器干净环境上实验也是失败的...
我先尝试一下非 ts 版吧,祝thinkjs越做越好

**Comment by welefen** [comment]
Fixed by https://github.com/thinkjs/thinkjs/commit/b902e701cf733813da31dd61f754e34056507368
