### ISSUE TITLE
[2.2.16]在postgresql中使用自定义主键(比如row_id)插入数据失败

### ISSUE THREAD

**Issue by rocwzp** [thinkjs/thinkjs#568]
## DESC
使用thinkjs v2.2.16和Postgresql来保存数据，model使用自定义的主键row_id，但调用model.add()时返回错误，错误信息如下：

[2017-02-17 16:24:46] [Error] error: column "id" does not exist
    at Connection.parseE (node_modules\pg\lib\connection.js:554:11)
    at Connection.parseMessage (node_modules\pg\lib\connection.js:381:17)
    at Socket.<anonymous> (node_modules\pg\lib\connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

我查看了thinkjs v2.2.16的源码，发现在src\adapter\db\postgresql.js中的execute(sql)函数中，insert语句返回的主键是hard-code的，并没有根据model的配置来动态的生成sql，比如row_id，所以insert语句执行失败。代码的具体位置请见注释。

@welefen 能否尽量在下一版本修复这个问题？多谢！

```js
execute(sql){
    this.sql = sql;
    let insertInto = 'insert into ';
    let prefix = sql.slice(0, insertInto.length).toLowerCase();
    let isInsert = false;
    if(prefix === insertInto){
      sql += ' RETURNING id';     // pk字段名是hard code
      isInsert = true;
    }
    return this.socket(sql).execute(sql).then(data => {
      if(isInsert){
        this.lastInsertId = data.rows[0].id;    // pk字段名是hard code
      }
      return data.rowCount || 0;
    });
  }

```

## ENV
Platform:
    Win 10
Node.js Version:
    7.5.0
ThinkJS Version:
    2.2.16

**Comment by welefen** [comment]
这个还不太好弄，execute 处理的时候并不知道数据表的 primary key

**Comment by lizheming** [comment]
It have been fixed in ThinkJS 3 https://github.com/thinkjs/think-model-postgresql/blob/master/lib/parser.js#L116-L120, you can upgrade to 3.
