### ISSUE TITLE
template not found: C:\CODING\Test\view\home\index_index.html

### ISSUE THREAD

**Issue by Messilimeng** [thinkjs/thinkjs#662]
## DESC

view.js type 改成 nunjucks 后 运行就报错

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
重启下服务还有这个报错么？

**Comment by Messilimeng** [comment]
报错 @welefen

**Comment by welefen** [comment]
贴下具体错误信息

**Comment by Messilimeng** [comment]
[2017-06-05 17:29:17] [Error] Error: template not found: E:\xydash\dash\view\home\index_index.html
    at createTemplate (E:\xydash\dash\node_modules\nunjucks\src\environment.js:206:31)
    at next (E:\xydash\dash\node_modules\nunjucks\src\lib.js:210:13)
    at handle (E:\xydash\dash\node_modules\nunjucks\src\environment.js:252:25)
    at E:\xydash\dash\node_modules\nunjucks\src\environment.js:263:21
    at next (E:\xydash\dash\node_modules\nunjucks\src\lib.js:207:13)
    at Object.exports.asyncIter (E:\xydash\dash\node_modules\nunjucks\src\lib.js:214:5)
    at [object Object].Obj.extend.getTemplate (E:\xydash\dash\node_modules\nunjucks\src\environment.js:242:17)
    at [object Object].Obj.extend.render (E:\xydash\dash\node_modules\nunjucks\src\environment.js:304:14)
    at module.exports.render (E:\xydash\dash\node_modules\nunjucks\index.js:72:14)
    at E:\xydash\dash\node_modules\thinkit\lib\index.js:47:10
    at Promise._execute (E:\xydash\dash\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (E:\xydash\dash\node_modules\bluebird\js\release\promise.js:473:18)
    at new Promise (E:\xydash\dash\node_modules\bluebird\js\release\promise.js:77:14)
    at E:\xydash\dash\node_modules\thinkit\lib\index.js:46:12
    at _class._callee$ (E:\xydash\dash\node_modules\thinkjs\lib\adapter\template\nunjucks.js:91:48)
    at tryCatch (E:\xydash\dash\node_modules\thinkjs\node_modules\babel-runtime\regenerator\runtime.js:88:40)

**Comment by Messilimeng** [comment]
view.js
'use strict';
/**
 * template config
 */
export default {
  type: 'nunjucks',
  content_type: 'text/html',
  file_ext: '.html',
  file_depr: '_',
  root_path: think.ROOT_PATH + '/view',
  adapter: {
    nunjucks: {}
  }
};

**Comment by Messilimeng** [comment]
![a2y_ j 2c rjf q172x h l](https://cloud.githubusercontent.com/assets/12272166/26778751/37513518-4a15-11e7-9a10-f7f65d5ed948.png)

**Comment by Messilimeng** [comment]
我不知道 我是不是还有别的什么没有配置

**Comment by welefen** [comment]
把 index_index.html 里换成一个最基本的内容看下呢？如： hello word 啥的

**Comment by Messilimeng** [comment]
我试试

**Comment by Messilimeng** [comment]
还是不行啊

**Comment by junmaqiang** [comment]
@Messilimeng  如果不是多模块项目的话应该是路径问题 把 view/home/index_index.html  变更为 view/home_index.html

**Comment by Messilimeng** [comment]
@junmaqiang 直接上3.0了 不用这个了

**Comment by yangqianghui** [comment]
如果是windows环境，路径要用双右划线！
export default {
  type: 'nunjucks',
  content_type: 'text/html',
  file_ext: '.html',
  file_depr: '_',
  root_path: think.ROOT_PATH + '\\view',
  adapter: {
      nunjucks: {
          prerender: (nunjucks, env) => {
              console.log('prerender inside');
              console.log(env);
          }
      }
  }
};
