### ISSUE TITLE
关于Postgresql 的连接失效问题

### ISSUE THREAD

**Issue by UtillYou** [thinkjs/thinkjs#687]
## DESC
这个问题大概在一年前我发现并解决过，现象为连接8小时候报错：
This socket is closed.
定位文件为 adapter/socket/postgresql.js
当时是因为判断依据错误。当时判断依据为

```javascript
if(err.message === 'This socket is closed.'){
```

事实上应该采用这样的判断

```javascript
if(err.code === 'EPIPE'){
```

最近发现又出现了。我发现是因为将
```this.release()```
这句代码位置提前了，原来是这样：

```javascript
//when socket is closed, try it
      if(err.message === 'This socket is closed.'){
        this.close();
        return this.query(sql);
      }

      this.release();
```

现在是这样：

```javascript
this.release();

      //when socket is closed, try it
      if(err.code === 'EPIPE'){
        this.close();
        return this.query(sql);
      }
```

不知道是刻意为之还是敲错了？

## ENV

Platform:centos

Node.js Version:4

ThinkJS Version:2

**Comment by UtillYou** [comment]
我通过跟踪错误日志，发现err返回的错误对象的code已不再是 EPIPE 而是ECONNRESET，具体错误如下

```
 socket close error { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
 [2017-07-01 00:10:51] [Error] Error: Connection reset. http://www.thinkjs.org/doc/error_message.html#econnreset
 at exports._errnoException (util.js:870:11)
 at TCP.onread (net.js:552:26)

```

是否需要添加对 ECONNRESET 的判断？

**Comment by UtillYou** [comment]
@welefen 有时间抽空看一下这个问题吗？我是用最新版的thinkjs链接postgresql，没过8小时就会报connectionreset 错误

**Comment by welefen** [comment]
我们尽快在 2.2.20 版本中修复这个问题

**Comment by UtillYou** [comment]
多谢，我们一直将thinkjs用于生产环境，多谢你们的努力

**Comment by welefen** [comment]
@UtillYou 刚提交的 commit 请帮忙验证下看是否还有问题
