### ISSUE TITLE
Thinkjs 3.0 ENFILE: file table overflow

### ISSUE THREAD

**Issue by libery** [thinkjs/thinkjs#704]
## DESC
用thinkjs开发的程序，运行一段时间就会报如下错误：

[2017-07-11 18:05:16.135] [INFO] - GET /xxx/list 200 97ms
fs.js:896
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENFILE: file table overflow, scandir '/Users/test/Documents/xxx/src'
    at Object.fs.readdirSync (fs.js:896:18)
    at Object.getdirFiles (/Users/test/Documents/xxx/node_modules/think-helper/index.js:429:18)
    at options.srcPath.forEach (/Users/test/Documents/xxx/node_modules/think-watcher/index.js:83:29)
    at Array.forEach (native)
    at Watcher.getChangedFiles (/Users/test/Documents/xxx/node_modules/think-watcher/index.js:80:21)
    at Timeout.detectFiles [as _onTimeout] (/Users/test/Documents/xxx/node_modules/think-watcher/index.js:153:31)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! thinkjs-application@1.0.0 start: `node development.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thinkjs-application@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## ENV

Platform:
MacOS Sierra
Node.js Version:
v8.0.0
ThinkJS Version:
3.0.0beta2

**Comment by welefen** [comment]
这是同时打开的文件数有限制，解决方案参考： http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit
