### ISSUE TITLE
customized adapter compiled error in 3.0

### ISSUE THREAD

**Issue by dsonet** [thinkjs/thinkjs#721]
## DESC
when I added a customized adapter, it got error like this:
(Whatever I implement the adapter, it consist show the following error)

```
D:\wwwroot\app\adapter\session\jwt.js.map:2
    "version": 3,
             ^
SyntaxError: Unexpected token :
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at exports.interopRequire (D:\wwwroot\node_modules\think-loader\loader\util.js:14:13)
    at files.forEach.file (D:\wwwroot\node_modules\think-loader\loader\config.js:53:31)
    at Array.forEach (native)
    at Config.loadAdapter (D:\wwwroot\node_modules\think-loader\loader\config.js:45:11)
    at Config.load (D:\wwwroot\node_modules\think-loader\loader\config.js:143:28)
    at Loader.loadConfig (D:\wwwroot\node_modules\think-loader\index.js:37:27)
    at thinkLoader.loadAll (D:\wwwroot\node_modules\thinkjs\lib\loader.js:90:45)
```

## ENV

Platform:

Node.js Version:

ThinkJS Version:3.0 beta (latest)

**Comment by welefen** [comment]
Fixed, please upgrade `think-loader` version to  1.0.12

**Comment by dsonet** [comment]
Just figure it out, you commit already.
