### ISSUE TITLE
think-router    Cannot read property 'endsWith' of null 

### ISSUE THREAD

**Issue by guangzhoujason** [thinkjs/thinkjs#739]
程序开着，经常会出现如下错误

检测到 Node.js v8.1.4，因此使用检查器协议调试。
node development.js 
[2017-07-26 15:59:47.411] [INFO] - Server running at http://127.0.0.1:8888
[2017-07-26 15:59:47.414] [INFO] - ThinkJS version: 3.0.0-beta3
[2017-07-26 15:59:47.415] [INFO] - Enviroment: development
[2017-07-26 15:59:47.415] [INFO] - Workers: 4
TypeError: Cannot read property 'endsWith' of null
    at suffix.some.item (/Users/Jason/Documents/project/api/v3/node_modules/think-router/router.js:62:46)
    at Array.some (native)
    at Router.getPathname (/Users/Jason/Documents/project/api/v3/node_modules/think-router/router.js:61:14)
    at new Router (/Users/Jason/Documents/project/api/v3/node_modules/think-router/router.js:34:26)
    at router (/Users/Jason/Documents/project/api/v3/node_modules/think-router/index.js:74:22)
    at dispatch (/Users/Jason/Documents/project/api/v3/node_modules/koa-compose/index.js:42:32)
    at next (/Users/Jason/Documents/project/api/v3/node_modules/koa-compose/index.js:43:18)
    at _callee$ (/Users/Jason/Documents/project/api/v3/node_modules/koa2-cors/dist/index.js:134:22)
    at tryCatch (/Users/Jason/Documents/project/api/v3/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/Jason/Documents/project/api/v3/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/Jason/Documents/project/api/v3/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/Jason/Documents/project/api/v3/node_modules/koa2-cors/dist/index.js:9:191)
    at /Users/Jason/Documents/project/api/v3/node_modules/koa2-cors/dist/index.js:9:437
    at Promise._execute (/Users/Jason/Documents/project/api/v3/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/Jason/Documents/project/api/v3/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/Users/Jason/Documents/project/api/v3/node_modules/bluebird/js/release/promise.js:77:14)
    at /Users/Jason/Documents/project/api/v3/node_modules/koa2-cors/dist/index.js:9:99
    at /Users/Jason/Documents/project/api/v3/node_modules/koa2-cors/dist/index.js:154:19
    at dispatch (/Users/Jason/Documents/project/api/v3/node_modules/koa-compose/index.js:42:32)
    at next (/Users/Jason/Documents/project/api/v3/node_modules/koa-compose/index.js:43:18)
    at parseBody.then.body (/Users/Jason/Documents/project/api/v3/node_modules/think-payload/index.js:59:14)
    at tryCatcher (/Users/Jason/Documents/project/api/v3/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Jason/Documents/project/api/v3/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/Jason/Documents/project/api/v3/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/Users/Jason/Documents/project/api/v3/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/Users/Jason/Documents/project/api/v3/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/Jason/Documents/project/api/v3/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/Jason/Documents/project/api/v3/node_modules/bluebird/js/release/async.js:17:14)
[2017-07-26 16:00:00.047] [INFO] - GET  200 26ms

**Comment by welefen** [comment]
报错的时候访问的页面 URL 是啥？

**Comment by welefen** [comment]
@lushijie 这是 `think-router` 里 `this.ctx.path` 为 `null` 导致的，查下为啥出现这个情况，然后做下兼容

**Comment by lushijie** [comment]
在 8.1.4 查看暂未复现本问题，目前针对这种情况加了兼容处理，请更新到 think-router@1.0.15

**Comment by welefen** [comment]
@guangzhoujason 请更新 `think-router@1.0.15` 看是否还有该问题？

**Comment by guangzhoujason** [comment]
观察下

**Comment by welefen** [comment]
@guangzhoujason 还有问题么？没问题的话先关闭 issue
