### ISSUE TITLE
 TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by guangzhoujason** [thinkjs/thinkjs#743]
## DESC

```
 TypeError: Cannot read property 'get' of undefined
      at Object.config (/Users/Jason/Documents/project/api/v3/node_modules/think-config/index.js:77:18)
      at Object.config (/Users/Jason/Documents/project/api/v3/node_modules/thinkjs/lib/extend/context.js:153:18)
      at Object.isJsonp (/Users/Jason/Documents/project/api/v3/node_modules/thinkjs/lib/extend/context.js:69:32)
      at Tracer.run (/Users/Jason/Documents/project/api/v3/node_modules/think-trace/lib/tracer.js:115:59)
      at tracer.getTemplateContent.then.then.catch.err (/Users/Jason/Documents/project/api/v3/node_modules/think-trace/lib/index.js:35:23)
      at tryCatcher (/Users/Jason/Documents/project/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/Jason/Documents/project/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
      at Promise._settlePromise (/Users/Jason/Documents/project/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
      at Promise._settlePromise0 (/Users/Jason/Documents/project/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
      at Promise._settlePromises (/Users/Jason/Documents/project/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:679:18)
      at Async._drainQueue (/Users/Jason/Documents/project/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:138:16)
      at Async._drainQueues (/Users/Jason/Documents/project/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
      at Immediate.Async.drainQueues (/Users/Jason/Documents/project/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
      at runCallback (timers.js:800:20)
      at tryOnImmediate (timers.js:762:5)
      at processImmediate [as _immediateCallback] (timers.js:733:5)
```

## ENV

Platform:
mac
Node.js Version:
8.4
ThinkJS Version:

3.0

**Comment by welefen** [comment]
项目是单模块还是多模块，怎么调用报的错误？

**Comment by guangzhoujason** [comment]
多模块的。。。
直接访问 地址，没有带 controler
比如
http://localhost:8306/

**Comment by welefen** [comment]
已经修复，需要更新  think-config 模块版本到 1.0.4
