### ISSUE TITLE
求pagination插件放到adapter里面的用法

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#745]
我用的是thinkjs 3.0构建的项目,
感觉官方提供的think-pagination 很好用,
但是我发现如果在controller下面用pagination的话,每一次都调用一下很是繁琐,
所以我想把分页组件做到 adapter里面,我的配置如下
```js
// src/common/adapter.js
const pagination = require('think-pagination');
/**
 * pages adapter config
 * @type {Object}
 */
exports.pages = {
    type: 'pagination',
    common: {
        desc: false, // show description
        pageNum: 2,
        url: '', // page url, when not set, it will auto generated
        class: '', // pagenation extra class
    },
    pagination: {
        handle: pagination,
        text: {
            next: 'Next',
            prev: 'Prev',
            total: 'count: __COUNT__ , pages: __PAGE__'
        }
    }
};
```

请问我在controller 下面如何使用呢?
```js
// src/member/controller/user.js
// 引入基类
const Base = require('./base.js');
// 用户类
module.exports = class extends Base {
    // 列表
    async indexAction() {
        let data = await this.model('users').page(this.get('page')).countSelect();
        const html = pagination(data, this.ctx, {});
        // 给模板赋值
        this.assign('pagination', html);
        this.assign('title', '用户列表');
        this.assign('items', data);
        return this.display();
    };
    // 图表
    async chartAction() {
        // 给模板赋值
        this.assign('title', '用户统计');
        return this.display();
    }
};
```

**Comment by welefen** [comment]
这个没必要做成 Adapter，并且即使做成了 Adapter 也还是需要在用的地方调用一次，跟现在调用一次没什么区别的

**Comment by junmaqiang** [comment]
那请问下, 
我想把官方提供的think-pagination 里面的index.js 文件抽取出来
做成一个extend 应该如何调用? 放在哪个目录? 我是用了,控制器分组

**Comment by junmaqiang** [comment]
![1](https://user-images.githubusercontent.com/1819457/28818639-448396f4-76de-11e7-8cf5-45091c73adfa.png)

**Comment by welefen** [comment]
Extend 如果放在项目的 extend 目录下，给 controller 扩展方法的话，那么文件为 `src/extend/controller.js`

```js
module.exports = {
    pagination() {
       
    }
}
```

这样 controller 里可以直接用 `this.pagination` 方法了。

**Comment by junmaqiang** [comment]
您的意思是不是我要改动两个地方
1, `src/项目目录/extend/pagination.js`  这是功能实现的地方
2,`src/extend/controller.js` 这是抛出方法的地方

是这样? @welefen

**Comment by welefen** [comment]
不需要 pagination.js 文件，直接在 extend/controller.js 里实现就可以了

**Comment by welefen** [comment]
这个文件导出 pagination 方法

**Comment by junmaqiang** [comment]
我按照方法这么操作的
还提示我未定义这个方法! 
```
TypeError: this.pagination is not a function
    at Object.indexAction (/Users/ajun/web/thinkjs-admin/src/adminis/controller/user.js:8:27)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[2017-08-02 00:04:56.364] [INFO] - GET /adminis/user/index?page=6 200 103ms
```
下面是我的代码目录情况!
![22](https://user-images.githubusercontent.com/1819457/28835236-454556e8-7717-11e7-96f6-d5f005e499a4.png)

```
// src/extend/controller.js 

const helper = require('think-helper');

/**
 * get page url
 * @param  {Object} options []
 * @param  {Object} http    []
 * @return {String}         []
 */
const getPageUrl = (options, ctx) => {
    let pageUrl = options.url;
    if (!pageUrl) {
        let prefix = (options.prefix || '') + '?';
        const querys = [];
        for (const name in ctx.query) {
            if (name === 'page') {
                continue;
            }
            querys.push(helper.escapeHtml(name) + '=' + helper.escapeHtml(ctx.query[name]));
        }
        prefix += querys.join('&');
        if (querys.length) {
            prefix += '&';
        }
        pageUrl = prefix + 'page=__PAGE__';
    }
    return pageUrl;
};

/**
 * get page index
 * @param  {Object} pagerData []
 * @param  {Object} options   []
 * @return {Array}           []
 */
const getPageIndex = (pagerData, options) => {
    const num = options.pageNum || 2;
    const page = pagerData.currentPage | 0 || 1;
    const totalPages = pagerData.totalPages;
    const pageIndex = [];
    let start = page - num;
    let stop = page + num;

    if (start <= 1) {
        start = 1;
        stop = start + num * 2 + 1;
    }

    if (stop >= totalPages) {
        stop = totalPages;
        start = totalPages - num * 2 - 1;
    }

    for (let i = start; i <= stop; i++) {
        if (i >= 1 && i <= totalPages) {
            pageIndex.push(i);
        }
    }
    return pageIndex;
};
/**
 * thinkjs pagenation 
 * @param  {Object} pagerData [pagerData by countSelect]
 * @param  {Object} ctx      []
 * @return {String}          []
 */
module.exports = {
    pagination(pagerData, ctx, options) {
        if (pagerData.totalPages <= 1) return '';

        options = Object.assign({
            desc: false, // show desc
            pageNum: 2,
            url: '',
            class: {
                ul: 'justify-content-end',
                    li: 'page-item',
                    a: 'page-link',
            },
            text: {
                next: '上一页',
                prev: '下一页',
                total: 'count: __COUNT__ , pages: __PAGE__'
            }
        }, options);

        const pageUrl = getPageUrl(options, ctx);
        const currentPage = pagerData.currentPage | 0 || 1;

        let html = `<ul class="pagination">`;
        if (options.class.ul) {
            html = `<ul class="pagination ${options.class.ul}">`;
        }
        if (options.desc) {
            const total = options.text.total.replace('__COUNT__', pagerData.count).replace('__PAGE__', pagerData.totalPages);
            html += `<li class="disabled ${options.class.li}"><span>${total}</span></li>`;
        }
        if (currentPage > 1) {
            html += `<li class="prev ${options.class.li}"><a class="${options.class.a}" href="${pageUrl.replace('__PAGE__', currentPage - 1)}">${options.text.prev}</a></li>`;
        }

        const pageIndex = getPageIndex(pagerData, options);
        if (pageIndex[0] > 1) {
            html += `<li class="${options.class.li}"><a class="${options.class.a}" href="${pageUrl.replace('__PAGE__', 1)}">1</a></li>`;
        }
        if (pageIndex[0] > 2) {
            html += `<li class="disabled ${options.class.li}"><span>...</span></li>`;
        }

        for (let i = 0, length = pageIndex.length; i < length; i++) {
            const p = pageIndex[i];
            if (p === currentPage) {
                html += `<li class="active ${options.class.li}"><a class="${options.class.a}" href="${pageUrl.replace('__PAGE__', p)}">${p}</a></li>`;
            } else {
                html += `<li class="${options.class.li}" ><a class="${options.class.a}" href="${pageUrl.replace('__PAGE__', p)}">${p}</a></li>`;
            }
        }
        if (pageIndex.length > 1) {
            const last = pageIndex[pageIndex.length - 1];
            if (last < (pagerData.totalPages - 1)) {
                html += `<li class="disabled ${options.class.li}"><span>...</span></li>`;
            }
            if (last < pagerData.totalPages) {
                html += `<li class="${options.class.li}"><a class="${options.class.a}" href="${pageUrl.replace('__PAGE__', pagerData.totalPages)}">${pagerData.totalPages}</a></li>`;
            }
        }
        if (currentPage < pagerData.totalPages) {
            html += `<li class="next ${options.class.li}"><a class="${options.class.a}" href="${pageUrl.replace('__PAGE__', currentPage + 1)}">${options.text.next}</a></li>`;
        }
        return html;
    }
};

```

**Comment by welefen** [comment]
你是多模块的项目？ 那 extend 要放在 `src/common/extend` 下

**Comment by junmaqiang** [comment]
哈哈, 确实是多模块项目! 
我说呢,咋有点怪怪的! 现在可以了,问题解决了! 谢谢  @welefen

**Comment by welefen** [comment]
@junmaqiang 已在文档上说明多模块下的路径

**Comment by welefen** [comment]
@junmaqiang 你现在是直接把 `think-pagination` 代码拿过来改的？欢迎把 `think-pagination` 改造为 Extend，然后发个 pull request
