### ISSUE TITLE
在写单元测试时，测试controller时，action中调用this.display(),报错：Error: can't find template file 

### ISSUE THREAD

**Issue by flftfqwxf** [thinkjs/thinkjs#758]
## DESC

在写单元测试时，测试controller时，action中调用this.display(),报错：Error: can't find template file 
project/mockserver-new/view///.nunj`

完整代码如下：

```js
'use strict';
var assert = require('assert');
var path = require('path');
var fs = require('fs');
var http = require('http');
var thinkjs = require('thinkjs');
var ROOT_PATH = path.dirname(__dirname);
thinkjs.load({
    ROOT_PATH: ROOT_PATH,
    APP_PATH: ROOT_PATH + think.sep + 'app',
    RUNTIME_PATH: ROOT_PATH + think.sep + 'runtime',
    RESOURCE_PATH: ROOT_PATH + think.sep + 'www'
});
//get http object
var getHttp = function(options) {
    var req = new http.IncomingMessage();
    req.headers = {
        'host': 'http://127.0.0.1:8033',
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0) AppleWebKit',
    };
    req.method = 'GET';
    req.httpVersion = '1.1';
    req.url = 'project/add';
    var res = new http.ServerResponse(req);
    res.write = function() {
        return true;
    }
    return think.http(req, res).then(function(http) {
        if (options) {
            for (var key in options) {
                http[key] = options[key];
            }
        }
        return http;
    })
}
describe('unit test', function() {
    it('test controller', function(done) {
        getHttp().then(function(http) {
            var instance = think.controller('project', http, 'home');
            return instance.testAction().then((data) => {
                console.log(data)
                done()
            }).catch(error => {
                console.log(error)
                done()
            })
        })
    })
});
```
testAction:
```
 async testAction() {

        //auto render template file index_index.html
        return this.display();
    }
```

报错：
```
[Error] Error: can't find template file `/Users/xxx/project/mockserver-new/view///.nunj`
    at _class._callee2$ (/Users/leixianhua/project/mockserver-new/node_modules/.thinkjs@2.2.19/lib/core/view.js:226:21)
    at tryCatch (/Users/leixianhua/project/mockserver-new/node_modules/.babel-runtime@6.6.1/regenerator/runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/leixianhua/project/mockserver-new/node_modules/.babel-runtime@6.6.1/regenerator/runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/leixianhua/project/mockserver-new/node_modules/.babel-runtime@6.6.1/regenerator/runtime.js:121:21)
    at step (/Users/leixianhua/project/mockserver-new/node_modules/.babel-runtime@6.6.1/helpers/asyncToGenerator.js:17:30)
    at /Users/leixianhua/project/mockserver-new/node_modules/.babel-runtime@6.6.1/helpers/asyncToGenerator.js:28:20
```
## ENV
dev
Platform:
MAC
Node.js Version:
6.9.1
ThinkJS Version:
v2.2.12

**Comment by welefen** [comment]
你这个绕过了路由解析，http 对象上缺少 http.module, http.controller, http.action 等属性

**Comment by flftfqwxf** [comment]
那如何解决？

**Comment by welefen** [comment]
给 http 对象赋值，或者 display 的时候指定参数
