### ISSUE TITLE
[think-model] 更新v1.0.3 后countSelect() 以及 事务的问题

### ISSUE THREAD

**Issue by tigerui** [thinkjs/thinkjs#769]
## DESC

> 事务

```
const Base = require('./base.js');

module.exports = class extends Base {
  async indexAction() {

  	let model = this.model('log')
  	try {
  		await model.startTrans()
  		let res = await model.where({ id: 10 }).update({
  			text: '123123123123123123'
  		})
  		await model.commit(model.connection)
  		return this.success()
  	} catch(e) {
  		console.log(e)
  		await model.rollback()
  		return this.fail()
  	}
  }
}
```

`SQL: START TRANSACTION, Time: 26ms`
之后没有反应，也没有看到新的连接。

> countSelect()
SQL: SELECT COUNT(mt_im_converse.id)  主键实际是  ic_id

> 补充
```
//model adapter config
const mysql = require('think-model-mysql');
exports.model = {
  type: 'mysql',
  common: {
    logConnect: isDev,
    logSql: isDev,
    logger: msg => think.logger.info(msg)
  },
  mysql: {
    handle: mysql, // Adapter handle
    user: 'root', // 用户名
    password: '', // 密码
    database: 'mengti', // 数据库
    host: 'mysql.rds.aliyuncs.com', // host 
    port: 3306, // 端口
    connectionLimit: 1, // 连接池的连接个数，默认为 1
    prefix: 'mt_', // 数据表前缀，如果一个数据库里有多个项目，那项目之间的数据表可以通过前缀来区分
  }
}
```

## ENV

Platform:

Node.js Version:

ThinkJS Version:
beta4
think-model v1.0.3
think-model-mysql v1.0.3

**Comment by welefen** [comment]
贴下具体的代码，主键不是 id 的话需要自己设置

**Comment by tigerui** [comment]
@welefen  已贴代码

**Comment by tigerui** [comment]
@welefen  能否实现自动获得主键，或者 countSelect 支持传入字段名，这样很不方便，还多出很多model/model.js

**Comment by welefen** [comment]
@tigerui  我们优化下这块

**Comment by tigerui** [comment]
辛苦 😆

**Comment by tigerui** [comment]
没有事务，我们基本上停下来了 😭

**Comment by welefen** [comment]
今天会修复这个问题

**Comment by tigerui** [comment]
six six six

**Comment by welefen** [comment]
事务的问题已经修复，请更新 think-model-abstract  think-model-mysql 到最新版本

**Comment by welefen** [comment]
模型主键需要不想写模型文件的话，还可以通过 `_pk` 属性设置主键，具体见：https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-c88

**Comment by tigerui** [comment]
@welefen

**Comment by tigerui** [comment]
@welefen 还是上面使用事务的例子
```
TypeError: Cannot read property 'startTrans' of undefined
    at Mysql.startTrans (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/think-model-abstract/index.js:105:22)
    at Model.startTrans (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model/lib/model.js:886:22)
    at /Users/charmtiger/Documents/WORK/thinkjs/mengti/src/controller/test.js:9:17
```

**Comment by tigerui** [comment]
@welefen  知道了 ,think-model-mysql 内依赖的  think-model-abstract 版本是 1.0.5，升级了就好了

**Comment by tigerui** [comment]
新版本远程连接数据库，很频繁的出现  Error: connect ETIMEDOUT

**Comment by tigerui** [comment]
```
[2017-08-12 11:20:58.045] [13068] [ERROR] - unhandledRejection, times: 1, pid: 13068
[2017-08-12 11:20:58.045] [13068] [ERROR] - { Error: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/mysql/lib/Connection.js:103:28)
```

**Comment by tigerui** [comment]
```
[2017-08-12 11:20:58.045] [13068] [ERROR] - unhandledRejection, times: 1, pid: 13068
[2017-08-12 11:20:58.045] [13068] [ERROR] - { Error: ER_BAD_FIELD_ERROR: Unknown column 'id' in 'field list'
    at Query.Sequence._packetToError (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model-mysql/node_modules/mysql/lib/Connection.js:103:28)
```
