### ISSUE TITLE
[3.0] 本地文件缓存 时常报错 Error no such file

### ISSUE THREAD

**Issue by tigerui** [thinkjs/thinkjs#778]
## DESC

本地文件缓存报错， 报错退出 业务无法继续
```
{ Error: ENOENT: no such file or directory, stat '/Users/charmtiger/Documents/WORK/thinkjs/mengti/runtime/cache/1/1efe3befc89dcd8d4a281ef67dbe73bd'
    at Error (native)
    at Object.fs.statSync (fs.js:987:18)
    at Object.isFile (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-helper/index.js:377:19)
    at FileStore.delete (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-store-file/index.js:95:17)
    at FileCache.delete (/Users/charmtiger/Documents/WORK/thinkjs/xxxxx/node_modules/think-cache-file/index.js:99:29)
    at Object.thinkCache [as cache] (/Users/charmtiger/Documents/WORK/thinkjs/xxxxx/node_modules/think-cache/cache.js:27:43)
    at /Users/charmtiger/Documents/WORK/thinkjs/xxxxx/src/model/user.js:12:17
    at next (native)
    at step (/Users/charmtiger/Documents/WORK/thinkjs/xxxxx/app/model/user.js:7:191)
    at /Users/charmtiger/Documents/WORK/thinkjs/xxxxx/app/model/user.js:7:361
    at tryCatcher (/Users/charmtiger/Documents/WORK/thinkjs/xxxxx/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/charmtiger/Documents/WORK/thinkjs/xxxxx/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/charmtiger/Documents/WORK/thinkjs/xxxxx/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/charmtiger/Documents/WORK/thinkjs/xxxxx/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/charmtiger/Documents/WORK/thinkjs/xxxxx/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/charmtiger/Documents/WORK/thinkjs/xxxxx/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/charmtiger/Documents/WORK/thinkjs/xxxxx/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/charmtiger/Documents/WORK/thinkjs/xxxxx/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/charmtiger/Documents/WORK/thinkjs/xxxxx/runtime/cache/1/1efe3befc89dcd8d4a281ef67dbe73bd' }
```

## ENV

Platform:
mac
Node.js Version:
node 8
ThinkJS Version:
Beta4

**Comment by welefen** [comment]
已经修复，升级 `think-helper@1.0.19`
