### ISSUE TITLE
3.0 think-mongo 出现Error: Cannot find module './lib/model.js'

### ISSUE THREAD

**Issue by brucecodezone** [thinkjs/thinkjs#790]
## DESC

> thinkjs-application@1.0.0 start /home/dashuai/workspace/gatedLaunch
> node development.js

{ Error: Cannot find module './lib/model.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dashuai/workspace/gatedLaunch/node_modules/think-mongo/index.js:3:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dashuai/workspace/gatedLaunch/app/config/extend.js:4:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32) code: 'MODULE_NOT_FOUND' }

## ENV ubuntu 16.4

Platform:chrome

Node.js Version:8.0

ThinkJS Version:3.0

**Comment by brucecodezone** [comment]
@welefen

**Comment by zhengqingxin** [comment]
在 think-mongo@1.0.2 中修复了  感谢~
