### ISSUE TITLE
TypeError: this.config is not a function

### ISSUE THREAD

**Issue by guangzhoujason** [thinkjs/thinkjs#795]
## DESC

3.0最新版本，服务器隔一段时间，会输出如下错误日志

```
[2017-08-19 23:00:00.059] [2539] [INFO] - CLI  404 5ms

  TypeError: this.config is not a function
      at jsonp (/root/projext/api/v3/node_modules/thinkjs/lib/extend/context.js:79:36)
      at Tracer.run (/root/projext/api/v3/node_modules/think-trace/lib/tracer.js:123:46)
      at beforeTrace.then.then.catch.err (/root/projext/api/v3/node_modules/think-trace/lib/index.js:47:21)
      at tryCatcher (/root/projext/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/root/projext/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
      at Promise._settlePromise (/root/projext/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
      at Promise._settlePromise0 (/root/projext/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
      at Promise._settlePromises (/root/projext/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:679:18)
      at Async._drainQueue (/root/projext/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:138:16)
      at Async._drainQueues (/root/projext/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
      at Immediate.Async.drainQueues (/root/projext/api/v3/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
      at runCallback (timers.js:781:20)
      at tryOnImmediate (timers.js:743:5)
      at processImmediate [as _immediateCallback] (timers.js:714:5)
```

## ENV

Platform:
centos64
Node.js Version:
8.x
ThinkJS Version:
3.0

**Comment by welefen** [comment]
是在定时任务运行时报的错误？定时任务具体是怎么配置的呢？

**Comment by guangzhoujason** [comment]
没有配置定时任务
也是很奇怪，哪里触发的

**Comment by guangzhoujason** [comment]
定时任务，还是默认的

module.exports = [{
    interval: '10s',
    immediate: true,
    handle: () => {
      //do something
      //console.log('common interval 10s');
    }
  },

  {
    cron: '0 */1 * * *',
    handle: '',
    worker: 'one'
  }
]

**Comment by welefen** [comment]
是多模块项目么？能找到复现的方式么

**Comment by guangzhoujason** [comment]
是多模块项目

新建demo项目以后，我们只是加了接口
没有做其他

应该所有think-cli创建的都会出现，是很容易重现

**Comment by welefen** [comment]
未能复现，是调用了 jsonp 方法？

**Comment by lizheming** [comment]
这个错误是 `think-trace` 尝试使用 json 输出错误导致的，原因见该提交 https://github.com/thinkjs/think-trace/commit/043891bbf336d1dc1f54bb0f61bd25c89a4cc14b 已经在 1.0.13 版中修复了，请及时升级。
