### ISSUE TITLE
websocket: AssertionError [ERR_ASSERTION]: headers have already been sent

### ISSUE THREAD

**Issue by libery** [thinkjs/thinkjs#799]
## DESC

使用think-websocket和think-websocket-socket.io，访问时报错：

[2017-08-23 07:01:50.811] [1545] [INFO] - GET /websocket 200 12ms
{ AssertionError [ERR_ASSERTION]: headers have already been sent
    at Object.set status [as status] (websockettest/node_modules/koa/lib/response.js:85:5)
    at Object.status (websockettest/node_modules/delegates/index.js:92:31)
    at promise.then.data (websockettest/node_modules/think-controller/index.js:51:22)
    at tryCatcher (websockettest/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (websockettest/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (websockettest/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (websockettest/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (websockettest/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (websockettest/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (websockettest/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

## ENV

Platform:
macos
Node.js Version:
v8.0.0
ThinkJS Version:
3.0.0

**Comment by lushijie** [comment]
可否发一下以下内容以便定位问题：
1.websocket adapter 的配置文件
2.websocket client 端的代码
3.websocket server端的代码

**Comment by libery** [comment]
完整示例如附件
[归档.zip](https://github.com/thinkjs/thinkjs/files/1250991/default.zip)

**Comment by lushijie** [comment]
请更新 think-websocket-socket.io 到 1.0.1 版本

**Comment by libery** [comment]
更新以后，工作貌似正常了，但是会报另一个错误：
[2017-08-28 15:08:47.980] [52165] [ERROR] - TypeError: Cannot read property 'emit' of null
    at Socket.socketOnTimeout (_http_server.js:386:34)
    at emitNone (events.js:105:13)
    at Socket.emit (events.js:207:7)
    at Socket._onTimeout (net.js:401:8)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)

**Comment by lushijie** [comment]
我回北京之后立刻排查，谢谢

发自我的 iPhone

**Comment by lushijie** [comment]
好的，我回北京之后立刻排查，谢谢。明天答复




--
发自我的网易邮箱手机智能版



在 2017-08-28 15:14:17，liber <notifications@github.com> 写道：


更新以后，工作貌似正常了，但是会报另一个错误：
[2017-08-28 15:08:47.980] [52165] [ERROR] - TypeError: Cannot read property 'emit' of null
at Socket.socketOnTimeout (_http_server.js:386:34)
at emitNone (events.js:105:13)
at Socket.emit (events.js:207:7)
at Socket._onTimeout (net.js:401:8)
at ontimeout (timers.js:488:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:283:5)

**Comment by lushijie** [comment]
[html代码](https://p0.ssl.qhimg.com/t014af6636a96cc6c5a.jpg)
[配置文件代码](https://p0.ssl.qhimg.com/t01cca89c8a03ecc159.jpg)
[controller代码](https://p0.ssl.qhimg.com/t0199dbe6ec34fdea4d.jpg)
[运行结果1](https://p4.ssl.qhimg.com/t013f4cf892a072cb0c.jpg)
[运行结果2](https://p0.ssl.qhimg.com/t01a669ea143a9fe95a.jpg)

暂未重现你所说的问题，首先移除node_modules 重新安装最新的，如果还有问题请粘贴详细代码，谢谢

**Comment by lushijie** [comment]
长期无响应，关闭 issue
