### ISSUE TITLE
sqlite集成失败

### ISSUE THREAD

**Issue by TrumanDu** [thinkjs/thinkjs#807]
## DESC

使用sqlite 数据库，实现curd功能，报错如下：
```
TypeError: Cannot read property 'parseData' of undefined
    at SQLiteAdapter.parseData (E:\github\nav-dashboad\node_modules\think-model-abstract\index.js:90:23)
    at E:\github\nav-dashboad\node_modules\think-model\lib\model.js:433:42
    at next (native)
    at step (E:\github\nav-dashboad\node_modules\think-model\lib\model.js:1:191)
    at E:\github\nav-dashboad\node_modules\think-model\lib\model.js:1:361
    at tryCatcher (E:\github\nav-dashboad\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\github\nav-dashboad\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (E:\github\nav-dashboad\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromiseCtx (E:\github\nav-dashboad\node_modules\bluebird\js\release\promise.js:596:10)
    at Async._drainQueue (E:\github\nav-dashboad\node_modules\bluebird\js\release\async.js:143:12)
    at Async._drainQueues (E:\github\nav-dashboad\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (E:\github\nav-dashboad\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

```
前端页面数据能够提交到后台，保存数据就报错。
## ENV
adapter.js code

```js
const sqlite = require('think-model-sqlite');
exports.model = {
    type: 'sqlite',
    sqlite: {
        handle: sqlite, // Adapter handle
        path: path.join(think.ROOT_PATH, 'runtime/sqlite'), // sqlite 保存的目录
        database: 'data', // 数据库名
        connectionLimit: 1, // 连接池的连接个数，默认为 1
        prefix: '', // 数据表前缀，如果一个数据库里有多个项目，那项目之间的数据表可以通过前缀来区分
    }
}
```

index.js code:
```js
async addAction() {
        let name = this.post('name');
        let model = this.model('index');
         let id = await model.add({
             name: name
         });

        this.body = "hello world!" + model.name;
    }
```

model index.js code
数据库表名是indexInfo
```js
module.exports = class extends think.Model {
    get tableName() {
        return 'indexInfo';
    }
}
```
Platform:
window webstorm2017.2.1
Node.js Version:
v6.11.2
ThinkJS Version:
ThinkJS version: 3.0.0-beta4

**Comment by welefen** [comment]
提供下 `think-model-abstract` 和 `think-model-sqlite` 模块的版本

**Comment by TrumanDu** [comment]
ok ,it work for me ,thanks. pls update [API document    ]( https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#sqlite) type: 'mysql', to type: 'sqlite',
