### ISSUE TITLE
设置think-trace的contentType引起的错误

### ISSUE THREAD

**Issue by wstygk** [thinkjs/thinkjs#809]
我在设置think-trace的contentType后,运行程序引起如下错误
TypeError: this.config is not a function
      at json (/node_modules/thinkjs/lib/extend/context.js:94:22)
      at Tracer.run (node_modules/think-trace/lib/tracer.js:123:46)

**Comment by lizheming** [comment]
close with same issue https://github.com/thinkjs/thinkjs/issues/795
