### ISSUE TITLE
 compile file admin\config\config.js error

### ISSUE THREAD

**Issue by w419631622** [thinkjs/thinkjs#835]
## DESC

[Error] compile file admin\config\config.js error
Error: Couldn't find preset "es2015" relative to directory "admin\\config"
[2017-09-07 23:14:50]     at D:\houshijing\HelloThinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
[COMPILE]     at Array.map (native)
    at OptionManager.resolvePresets (D:\houshijing\HelloThinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
compile file admin\controller\base.js error    at OptionManager.mergePresets (D:\houshijing\HelloThinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (D:\houshijing\HelloThinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)

[2017-09-07 23:14:50] [COMPILE] compile file admin\controller\index.js error
    at OptionManager.init (D:\houshijing\HelloThinkjs\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\houshijing\HelloThinkjs\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\houshijing\HelloThinkjs\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\houshijing\HelloThinkjs\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at _class.compileByBabel (D:\houshijing\HelloThinkjs\node_modules\thinkjs\lib\util\watch_compile.js:180:22)
    at _class.compileFile (D:\houshijing\HelloThinkjs\node_modules\thinkjs\lib\util\watch_compile.js:101:14)
    at D:\houshijing\HelloThinkjs\node_modules\thinkjs\lib\util\watch_compile.js:312:26
    at Array.forEach (native)
    at _class.compile (D:\houshijing\HelloThinkjs\node_modules\thinkjs\lib\util\watch_compile.js:290:11)
    at _class.run (D:\houshijing\HelloThinkjs\node_modules\thinkjs\lib\util\watch_compile.js:346:10)
    at _class.compile (D:\houshijing\HelloThinkjs\node_modules\thinkjs\lib\index.js:523:14)
纯小白，从网上http://www.jianshu.com/p/bd389d2622ac 下载的一个demo，运行不起来，大神们给解决解决
## ENV

Platform:

Node.js Version: 8.1.3

ThinkJS Version:2.2.21

**Comment by w419631622** [comment]
自个解决了，npm install babel-preset-es2015 --save-dev下载一个标准

**Comment by welefen** [comment]
@w419631622 你的项目下有 .babelrc 文件？
不需要装这个 preset，你把 think-babel 模块升级下
