### ISSUE TITLE
升级到3.1.0之后报错

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#837]
```
> weijiao@0.0.1 start /Users/ajun/web/thinkjs-all-weijiao
> node development.js

TypeError: thinkCluster.isAgent is not a function
    at Application.run (/Users/ajun/web/thinkjs-all-weijiao/node_modules/thinkjs/lib/application.js:199:31)
    at Object.<anonymous> (/Users/ajun/web/thinkjs-all-weijiao/development.js:16:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

不晓得是啥原因,导致报此错误!

**Comment by junmaqiang** [comment]
升级到3.1.1 问题解决!
