### ISSUE TITLE
SocketIO Redis TypeError: Cannot read property 'encoder' of undefined

### ISSUE THREAD

**Issue by panda7603** [thinkjs/thinkjs#845]
## DESC
2017/09/12 thinkjs升级最新版本
按照git的配置配好socketio  启动提示没有 socket.io-redis
`Cannot find module 'socket.io-redis'`
于是
`npm install socket.io-redis`
再次启动
```
[2017-09-12 16:14:07.086] [9052] [ERROR][2017-09-12 16:14:07.086] [3228] [ERROR] - unhandledRejection, times: 1, pid: 9052
 - unhandledRejection, times: 1, pid: 3228
[2017-09-12 16:14:07.088] [8492] [ERROR] - unhandledRejection, times: 1, pid: 8492
[2017-09-12 16:14:07.089] [2792] [ERROR] - unhandledRejection, times: 1, pid: 2792
[2017-09-12 16:14:07.090] [3228] [ERROR][2017-09-12 16:14:07.090] [9052] [ERROR] - TypeError: Cannot read property 'encoder' of undefin
ed
    at Object.Adapter (F:\ws2\node_modules\socket.io-adapter\index.js:25:28)
    at Object.Redis [as adapter] (F:\ws2\node_modules\socket.io-redis\index.js:79:13)
    at new SocketIO (F:\ws2\node_modules\think-websocket-socket.io\index.js:17:30)
    at Application.app.on (F:\ws2\node_modules\think-websocket\index.js:18:16)
    at emitNone (events.js:110:20)
    at Application.emit (events.js:207:7)
    at think.beforeStartServer.catch.then.then (F:\ws2\node_modules\thinkjs\lib\application.js:150:17)
    at tryCatcher (F:\ws2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\ws2\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (F:\ws2\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (F:\ws2\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (F:\ws2\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (F:\ws2\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
 - TypeError: Cannot read property 'encoder' of undefined
    at Object.Adapter (F:\ws2\node_modules\socket.io-adapter\index.js:25:28)
    at Object.Redis [as adapter] (F:\ws2\node_modules\socket.io-redis\index.js:79:13)
    at new SocketIO (F:\ws2\node_modules\think-websocket-socket.io\index.js:17:30)
    at Application.app.on (F:\ws2\node_modules\think-websocket\index.js:18:16)
    at emitNone (events.js:110:20)
    at Application.emit (events.js:207:7)
    at think.beforeStartServer.catch.then.then (F:\ws2\node_modules\thinkjs\lib\application.js:150:17)
    at tryCatcher (F:\ws2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\ws2\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (F:\ws2\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (F:\ws2\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (F:\ws2\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (F:\ws2\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
[2017-09-12 16:14:07.094] [3228] [ERROR][2017-09-12 16:14:07.091] [8492] [ERROR][2017-09-12 16:14:07.095] [9052] [ERROR] - TypeError: C
annot read property 'encoder' of undefined
    at Object.Adapter (F:\ws2\node_modules\socket.io-adapter\index.js:25:28)
    at Object.Redis [as adapter] (F:\ws2\node_modules\socket.io-redis\index.js:79:13)
    at new SocketIO (F:\ws2\node_modules\think-websocket-socket.io\index.js:17:30)
    at Application.app.on (F:\ws2\node_modules\think-websocket\index.js:18:16)
    at emitNone (events.js:110:20)
    at Application.emit (events.js:207:7)
    at think.beforeStartServer.catch.then.then (F:\ws2\node_modules\thinkjs\lib\application.js:150:17)
    at tryCatcher (F:\ws2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\ws2\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (F:\ws2\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (F:\ws2\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (F:\ws2\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (F:\ws2\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
 - TypeError: Cannot read property 'encoder' of undefined
    at Object.Adapter (F:\ws2\node_modules\socket.io-adapter\index.js:25:28)
    at Object.Redis [as adapter] (F:\ws2\node_modules\socket.io-redis\index.js:79:13)
    at new SocketIO (F:\ws2\node_modules\think-websocket-socket.io\index.js:17:30)
    at Application.app.on (F:\ws2\node_modules\think-websocket\index.js:18:16)
    at emitNone (events.js:110:20)
    at Application.emit (events.js:207:7)
    at think.beforeStartServer.catch.then.then (F:\ws2\node_modules\thinkjs\lib\application.js:150:17)
    at tryCatcher (F:\ws2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\ws2\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (F:\ws2\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (F:\ws2\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (F:\ws2\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (F:\ws2\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
 - TypeError: Cannot read property 'encoder' of undefined
    at Object.Adapter (F:\ws2\node_modules\socket.io-adapter\index.js:25:28)
    at Object.Redis [as adapter] (F:\ws2\node_modules\socket.io-redis\index.js:79:13)
    at new SocketIO (F:\ws2\node_modules\think-websocket-socket.io\index.js:17:30)
    at Application.app.on (F:\ws2\node_modules\think-websocket\index.js:18:16)
    at emitNone (events.js:110:20)
    at Application.emit (events.js:207:7)
    at think.beforeStartServer.catch.then.then (F:\ws2\node_modules\thinkjs\lib\application.js:150:17)
    at tryCatcher (F:\ws2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\ws2\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (F:\ws2\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (F:\ws2\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (F:\ws2\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (F:\ws2\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
[2017-09-12 16:14:07.091] [2792] [ERROR][2017-09-12 16:14:07.096] [8492] [ERROR] - TypeError: Cannot read property 'encoder' of undefin
ed
    at Object.Adapter (F:\ws2\node_modules\socket.io-adapter\index.js:25:28)
    at Object.Redis [as adapter] (F:\ws2\node_modules\socket.io-redis\index.js:79:13)
    at new SocketIO (F:\ws2\node_modules\think-websocket-socket.io\index.js:17:30)
    at Application.app.on (F:\ws2\node_modules\think-websocket\index.js:18:16)
    at emitNone (events.js:110:20)
    at Application.emit (events.js:207:7)
    at think.beforeStartServer.catch.then.then (F:\ws2\node_modules\thinkjs\lib\application.js:150:17)
    at tryCatcher (F:\ws2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\ws2\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (F:\ws2\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (F:\ws2\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (F:\ws2\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (F:\ws2\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
 - TypeError: Cannot read property 'encoder' of undefined
    at Object.Adapter (F:\ws2\node_modules\socket.io-adapter\index.js:25:28)
    at Object.Redis [as adapter] (F:\ws2\node_modules\socket.io-redis\index.js:79:13)
    at new SocketIO (F:\ws2\node_modules\think-websocket-socket.io\index.js:17:30)
    at Application.app.on (F:\ws2\node_modules\think-websocket\index.js:18:16)
    at emitNone (events.js:110:20)
    at Application.emit (events.js:207:7)
    at think.beforeStartServer.catch.then.then (F:\ws2\node_modules\thinkjs\lib\application.js:150:17)
    at tryCatcher (F:\ws2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\ws2\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (F:\ws2\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (F:\ws2\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (F:\ws2\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (F:\ws2\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
[2017-09-12 16:14:07.096] [2792] [ERROR] - TypeError: Cannot read property 'encoder' of undefined
    at Object.Adapter (F:\ws2\node_modules\socket.io-adapter\index.js:25:28)
    at Object.Redis [as adapter] (F:\ws2\node_modules\socket.io-redis\index.js:79:13)
    at new SocketIO (F:\ws2\node_modules\think-websocket-socket.io\index.js:17:30)
    at Application.app.on (F:\ws2\node_modules\think-websocket\index.js:18:16)
    at emitNone (events.js:110:20)
    at Application.emit (events.js:207:7)
    at think.beforeStartServer.catch.then.then (F:\ws2\node_modules\thinkjs\lib\application.js:150:17)
    at tryCatcher (F:\ws2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\ws2\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (F:\ws2\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (F:\ws2\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (F:\ws2\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (F:\ws2\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues (F:\ws2\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
```
## ENV

Node.js Version:  8.2.1

ThinkJS Version:  3.0.0

**Comment by lushijie** [comment]
你能粘贴一下代码么？没看懂。 另你想要实现什么？

**Comment by panda7603** [comment]
这是个空的项目，不是实现什么，就是简单的搭一个这样的环境 。。。
[ws2.zip](https://github.com/thinkjs/thinkjs/files/1295665/ws2.zip)

**Comment by lushijie** [comment]
```js
// const socketRedis = require('socket.io-redis');
// const socketAdapter = socketRedis({ host: 'localhost', port: 6379 });

exports.websocket = {
  type: 'socketio',
  common: {
    // common config
  },
  socketio: {
    handle: socketio,
    // allowOrigin: null, // any origin is allowed by default
    // path: '/test', // `/socket.io` by default.
    adapter: null,
    messages: [{
      open: '/index/open', // websocket action when connected
      close: '/index/close', // websocket action when close
      sendMessage: '/index/sendMessage', //websocket addUser action when event is addUser
    }]
  }
};
```

src/config/adapter.js 中，先注释掉websocket 的 adapter, 关于如何使用 adpater， 请查看 socket.io 的文档

**Comment by panda7603** [comment]
```
const socketio = require('think-websocket-socket.io');
const redis = require('socket.io-redis');
const adapter1 = redis({ host: 'localhost', port: 6379 });
exports.websocket = {
  type: 'socketio',
  socketio: {
    // ...
    adapter: adapter1,
    // ...
  }
}
```

我是看到   thinkjs socketio git 上这样配置的

**Comment by lushijie** [comment]
请更新 think-websocket-socket.io 到 1.0.2 版本， 一个bug已经fix，谢谢

**Comment by panda7603** [comment]
[]~(￣▽￣)~*    谢谢！
