### ISSUE TITLE
如何配置把框架自己的log信息打印到指定的地方

### ISSUE THREAD

**Issue by xiaoyicn** [thinkjs/thinkjs#887]
## DESC
如下这种mysql没有启动错误的log，无法按照开发者的配置打印到指定的地方。
这种log，好像是框架用console.log打印出来的，不知道怎么控制。

### ENV
OS Platform: Windows 8
Node.js Version: 8.6
ThinkJS Version: 3.2.1

### 框架Log
```
{ Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
    --------------------
    at Protocol._enqueue (E:\Dev_Projects\backend\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at Protocol.handshake (E:\Dev_Projects\backend\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at PoolConnection.connect (E:\Dev_Projects\backend\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (E:\Dev_Projects\backend\node_modules\mysql\lib\Pool.js:48:16)
    at Promise (E:\Dev_Projects\backend\node_modules\think-helper\index.js:83:10)
    at Promise._execute (E:\Dev_Projects\backend\node_modules\thinkjs\node_modules\bluebird\js\release\
debuggability.js:272:9)
    at Promise._resolveFromExecutor (E:\Dev_Projects\backend\node_modules\thinkjs\node_modules\bluebird
\js\release\promise.js:473:18)
    at new Promise (E:\Dev_Projects\backend\node_modules\thinkjs\node_modules\bluebird\js\release\promi
se.js:77:14)
    at args (E:\Dev_Projects\backend\node_modules\think-helper\index.js:82:12)
    at ThinkMysql.getConnection (E:\Dev_Projects\backend\node_modules\think-mysql\index.js:70:64)
    at ThinkMysql.query (E:\Dev_Projects\backend\node_modules\think-mysql\index.js:179:17)
    at MysqlQuery.query (E:\Dev_Projects\backend\node_modules\think-model-abstract\lib\query.js:22:29)
    at MysqlQuery.select (E:\Dev_Projects\backend\node_modules\think-model-abstract\lib\query.js:150:29
)
    at Mysql.select (E:\Dev_Projects\backend\node_modules\think-model-abstract\index.js:87:23)
    at E:\Dev_Projects\backend\node_modules\think-model\lib\model.js:609:38
    at Generator.next (<anonymous>)
```

###正常可配置的log：
```
[2017-09-30 22:35:27.796] [7012] [INFO] - BLABLA
```

**Comment by lizheming** [comment]
think-trace 中间件的 error 参数配一下

```js
{
 error: err => think.log.error(err)
}
```

**Comment by xiaoyicn** [comment]
在开发环境，框架自有的info log可以打印到指定位置。
但在生产环境，log级别配置正确，这些log没有打印出来，该如何配置？
是不是也是类似在trace模块加入: 
{
 info: msg => think.log.info(msg)
}

**Comment by lizheming** [comment]
生产环境log是输出到文件的。

**Comment by xiaoyicn** [comment]
加在trace后OK，可以在production环境打印出不那么详实的错误了。
`
  {
    handle: 'trace',
    enable: !think.isCli,
    options: {
      error: (err: any) => think.logger.error(err),
      debug: isDev
    }
  },
`
