### ISSUE TITLE
如何配置think-trace在production环境去log更详细的错误信息

### ISSUE THREAD

**Issue by xiaoyicn** [thinkjs/thinkjs#892]
## DESC

think-trace在production环境去log error时，只有简单的一些信息，如何配置去获得更详细的错误信息，如果能细致到某一个文件的某一行更好。
当前配置：
`
  {
    handle: 'trace',
    enable: !think.isCli,
    options: {
      error: (err: any) => think.logger.error(err),
      debug: isDev,
    }
  },
`
### ENV

OS Platform: win8
Node.js Version: 8.6
ThinkJS Version: 3.2.1

### Log文件内容的期望结果、实际结果

期望：
[2017-10-03 12:26:34.147] [4424] [ERROR] - { Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
    --------------------
    at Protocol._enqueue (E:\Dev_Projects\backend\node_modules\mysql\lib\protocol\Protocol.js:141:48)
 ... ... ... ... 等等更多stack信息
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true }

实际结果：
[2017-10-03 12:26:54.995] [ERROR] [default] - { code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true }

**Comment by lizheming** [comment]
`debug = true` 即可，另外不建议在 production 环境中暴露详细的错误信息，容易给网站留下后门风险。
