### ISSUE TITLE
服务器上部署遇到  SyntaxError: Unexpected identifier 问题

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#896]
本地运行没事, 我不晓得在服务器上部署是不是还需要x执行权限?
我是git代码拉取到服务器上,
然后npm install
然后 npm start
接着就出现下面这些错误! 
提示: 好像是语法解析错误, 但是语法确实没有问题, 校验过!

```
> weixiao@0.0.1 start /home/wwwroot/node/e.weixiao.com
> node development.js

/home/wwwroot/node/e.weixiao.com/src/controller/adminis/activity.js:18
    async indexAction() {
          ^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at exports.interopRequire (/home/wwwroot/node/e.weixiao.com/node_modules/think-loader/loader/util.js:14:13)
    at files.forEach.file (/home/wwwroot/node/e.weixiao.com/node_modules/think-loader/loader/common.js:16:26)
    at Array.forEach (native)
    at Object.loadFiles (/home/wwwroot/node/e.weixiao.com/node_modules/think-loader/loader/common.js:12:11)
    at Object.load (/home/wwwroot/node/e.weixiao.com/node_modules/think-loader/loader/common.js:64:32)
    at Loader.loadController (/home/wwwroot/node/e.weixiao.com/node_modules/think-loader/index.js:49:19)
    at thinkLoader.loadData (/home/wwwroot/node/e.weixiao.com/node_modules/thinkjs/lib/loader.js:42:42)
```

**Comment by lushijie** [comment]
你看一下 app/controller/adminis/activity.js 下的 js 代码转化为 es5 代码了没有

**Comment by welefen** [comment]
需要将 app 目录的代码（src/ 目录编译后的代码）上线，或者线上 Node 版本 >= 7.6.0

**Comment by junmaqiang** [comment]
问题已经解决:  @welefen  @lushijie 
**原因:**  是node版本的问题 ( CentOS7服务器上用yum install nodejs 安装默认的是V6.11.1版本 )
 **解决方案:** 参考了这里 http://jingyan.baidu.com/article/29697b916b8a65ab20de3c99.html
