### ISSUE TITLE
有没有办法让某个Service对象一直存在？

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#915]
比如说，我创建了一个Service类，这个Service构造函数代价比较大，但整个项目只需要一个Service对象，现在的情况是，如果我在Controller里面通过think.service创建这个service的话，每接到一次请求都得构造一次，太难受了。

虽然说可以按照自己的需求自定义项目入口，让某个对象生命周期伴随整个进程一直都在，但那样又感觉不太“干净”

**Comment by KuoKongQingYun** [comment]
目前想到的就是自己写个node模块，然后require进来，因为require的js文件只会执行一次。
但还是希望thinkjs能有自己的办法。

我试过在controller定义文件的module.experts外面对service进行实例化，而不是在action方法里面，但这样会报错，应该是项目启动的时候service还不能用吧。

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/bootstrap.html#bootstrap 在 bootstrap 里面写到 global 去就好啦。另外 `require` 在多进程模式下并不是只执行一次哦，会执行进程数次的。

**Comment by KuoKongQingYun** [comment]
@lizheming 实测在Controller Class外部实例化不行，

![image](https://user-images.githubusercontent.com/3955922/31848165-2f7ad6c2-b65e-11e7-95bf-b07ba16ebec0.png)


TypeError: Cannot read property 'common' of undefined
    at Object.think.service.args [as service] (E:\data\Projects\FunyGo2\web\node_modules\thinkjs\lib\think.js:75:31)
    at Object.<anonymous> (E:\data\Projects\FunyGo2\web\app\wechat\controller\auth.js:4:20)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at exports.interopRequire (E:\data\Projects\FunyGo2\web\node_modules\think-loader\loader\util.js:14:13)
    at files.forEach.file (E:\data\Projects\FunyGo2\web\node_modules\think-loader\loader\common.js:16:26)
    at Array.forEach (<anonymous>)
    at Object.loadFiles (E:\data\Projects\FunyGo2\web\node_modules\think-loader\loader\common.js:12:11)
    at modules.forEach.item (E:\data\Projects\FunyGo2\web\node_modules\think-loader\loader\common.js:48:40)
    at Array.forEach (<anonymous>)
    at Object.load (E:\data\Projects\FunyGo2\web\node_modules\think-loader\loader\common.js:46:15)

**Comment by welefen** [comment]
@KuoKongQingYun 

```js
let service = null;
module.exports = class extends think.Controller {
   indexAction() {
     if(!service) {
        service = think.service('www', 'ddd')
     }
   }
}
```

可以先通过这种方式。但实际上实例化类的成本是很低的，没必要维持一个。

**Comment by KuoKongQingYun** [comment]
@welefen 好的，其实我是举得一个微信的例子，实际我的另一个service里需要模拟登陆然后维持一个cookie以及其他的一些中间数据，如果每次都实例化就很耗费时间了和内存了……

**Comment by KuoKongQingYun** [comment]
我个人想象中的Service应该像服务器那样一直“在线”，然后提供某些服务，而不是每次运行都要实例化，那样就感觉不太像是Service的感觉了。比方说我有个远程的服务，每次都有一个繁琐的登陆过程，以及保持登陆的方式，我写了一个Service来负责调用这个远程服务，如果每次都要实例化的话，代价太高了。一个简单的例子就是一个类即时通讯服务，平时需要一直发送心跳包来保持在线，但随时可以调用它进行发送或者接受数据，如果每次访问就“上线”-“发送”-“接受”-“离线”的话，就显得很不妥了。

是否会在以后的更新中加入这种长期保持“在线”的Service或者类似的功能呢？

**Comment by welefen** [comment]
@KuoKongQingYun 恩，我们后续调整下加载的顺序就可以支持这个功能

**Comment by KuoKongQingYun** [comment]
@welefen 感谢，如果方便的话，希望也能在bootstrap中的master和worker中实例化，
比如我在master.js中实例化service，通过消息传递，就能方便多进程共享同一个对象了。

**Comment by KuoKongQingYun** [comment]
实测，worker.js里可以实例化service，而master不能。如果在master.js中实例化service的话，会出现

`TypeError: Cannot read property 'length' of undefined
    at Object.think.service.args [as service] (E:\data\Projects\FunyGo2\web\node_modules\thinkjs\lib\think.js:74:24)`

我看了一下loader.js的代码，master进程不会加载控制器、服务、中间件等内容。
`
if (type !== 'master') {
      this.writeConfig(config);
      this.loadExtend();
      this.loadData();
      this.loadMiddleware();
      if (!isCli) {
        this.loadCrontab();
      }
    }
    think.loader.loadBootstrap(type);
`
但是实际使用确实有上述需求，比如我只需要一个service实例的时候，如果我写在worker.js里，多进程下就会有多个实例了，这种情况下我需要在master.js里实例化保证其只有一个。

**Comment by welefen** [comment]
@KuoKongQingYun master 里不应该有业务逻辑，只用来做分发。有业务逻辑会影响请求转发到 worker 里。

你升级 `thinkjs@3.2.3` 应该支持在 controller 的顶部直接 require service 了。

**Comment by KuoKongQingYun** [comment]
@welefen 好的，感谢。
