### ISSUE TITLE
网络环境变化后，查询数据库报错

### ISSUE THREAD

**Issue by tigerui** [thinkjs/thinkjs#920]
## DESC
本地环境翻墙回来后，就出现此问题
之前服务器也出现过，不过没有报错，之前是一段时间后，查询直接不返回，必须要重启thinkjs 服务才可以。不过很久没出现了。

```
[2017-10-26 12:14:27.574] [3984] [INFO] - SQL: SELECT * FROM `mt_user` WHERE ( `phone` = '12345678901' ) LIMIT 1, Time: 102ms
Error: update data is empty
    at /Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model/lib/model.js:556:31
    at Generator.next (<anonymous>)
    at step (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model/lib/model.js:1:191)
    at /Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/think-model/lib/model.js:1:361
    at tryCatcher (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/charmtiger/Documents/WORK/thinkjs/mengti/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

### ENV
development
OS Platform:
mac os
Node.js Version:
8.4
ThinkJS Version:
3.2.1
### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by welefen** [comment]
@tigerui 这是更新时数据字段都被过滤导致的，看下更新的数据里的字段在数据表里是不是存在

**Comment by tigerui** [comment]
又无法复现 😂

**Comment by welefen** [comment]
先关闭，后续复现后在处理
