### ISSUE TITLE
不知道是不是编译问题 服务器上老是出错

### ISSUE THREAD

**Issue by Messilimeng** [thinkjs/thinkjs#933]
## DESC
每次运行程序 node development 就直接报错
### ENV

OS Platform:
liunx centos 7.X
Node.js Version:
6.9.1
ThinkJS Version:
3.2.3
### code
const API = require('co-wechat-api');
 this.api = new API(this.config('wx_appID'), this.config('wx_appsecret'));
```js
// your code here
```
![image](https://user-images.githubusercontent.com/12272166/32152244-b8be5f20-bd5d-11e7-908d-9418bd490c16.png)

### error message
/root/aasd/node_modules/co-wechat-api/lib/api_common.js:59
this.getToken = getToken || async function () {
^^^^^^^^
SyntaxError: Unexpected token function
at Object.exports.runInThisContext (vm.js:76:16)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (/root/51work/node_modules/co-wechat-api/index.js:3:13)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
```
// your error message here
```

### more description
![image](https://user-images.githubusercontent.com/12272166/32152199-7eb42490-bd5d-11e7-9f8f-d8f986951e8a.png)

// your detail description

**Comment by lizheming** [comment]
你使用的 `co-wechat-api` 这个库没有使用 babel 编译，Node 6.9.1 默认不支持 async 语法。解决办法是要么升级你的 node 要么换库。

**Comment by Messilimeng** [comment]
@lizheming 升级到 7.x co-wechat-api 还是有错  但是 升级到8.x 就没有错了

**Comment by lizheming** [comment]
https://nodejs.org/en/blog/release/v8.0.0/#improved-support-for-promises
