### ISSUE TITLE
think-sequelize 重复定义relations报错

### ISSUE THREAD

**Issue by callmez** [thinkjs/thinkjs#942]
```js
class ExchangeOrder extends think.Sequel {

  get schema() {
    const DataTypes = think.Sequel.Sequel;

    return {
      attributes: {
        ...
      },
      relations: [
        {
          demo_relation: think.Sequel.Relation.BELONG_TO,
          options: {
            foreignKey: 'relation_id',
            as: 'relation'
          }
        },
      ]
    }
  }
}
```

```js
SequelizeAssociationError: You have used the alias pair in two separate associations. Aliased associations must have unique aliases.
    at BelongsTo.Association (/Volumes/File/go/demo/node_modules/sequelize/lib/associations/base.js:104:13)

// 出错代码是
if (source.hasAlias(options.as)) {
      throw new AssociationError(`You have used the alias ${options.as} in two separate associations. ` +
      'Aliased associations must have unique aliases.'
      );
    }
```

追了下代码发现问题是缓存后的`model`示例重复定义`relations`导致

默认情况下  `think.sequel('Model')` 的实例会存储relations并缓存在`models`中, 由于第一次实例化后`model.associations`是空的 所以`source.hasAlias(options.as) = false`不会报错, 而在以后的调用中会再次存储relations操作而导致`source.hasAlias(options.as)=true`抛出错误. 

请尽快修复, 谢谢!

**Comment by lushijie** [comment]
'以后的调用中会再次存储relations操作' 这里指的是再次实例化model? 可有具体的错误示例以便调试？

**Comment by lushijie** [comment]
[https://github.com/lushijie/thinkjs3-demo](https://github.com/lushijie/thinkjs3-demo)  里面有使用的demo，请细化一下你的问题，谢谢 @callmez

**Comment by callmez** [comment]
@lushijie 

```
class Demo extends think.Sequel {

  get schema() {
    const DataTypes = think.Sequel.Sequel;

    return {
      attributes: {
        ...
      },
      relations: [
        {
          demo_relation: think.Sequel.Relation.BELONG_TO,
          options: {
            foreignKey: 'relation_id',
            as: 'relation'
          }
        },
      ]
    }
  }
}
```

这个`demo`medel里定义了一个BELONG_TO的 `demo_relation`关系. 

```js
think.sequel('demo').findAll({
    include: [
          {
            model: think.sequel('demo_relation'),
            where: {
              is_open: 1
            },
            as: 'relation'
          }
        ]
})
```
当我做关联查询的时候一下, 以上代码 在应用第一次运行的时候不会报错, 
第二次执行就会报错
```
SequelizeAssociationError: You have used the alias pair in two separate associations. Aliased associations must have unique aliases.
    at BelongsTo.Association (/Volumes/File/go/demo/node_modules/sequelize/lib/associations/base.js:104:13)


// 出错代码是这样判断的
if (source.hasAlias(options.as)) {
      throw new AssociationError(`You have used the alias ${options.as} in two separate associations. ` +
      'Aliased associations must have unique aliases.'
      );
    }

```
我追了下代码, 当第一次`think.model('demo')`的时候, new完会和relations一次缓存到`models`中,在new的时候`source.associations` 是空的, 所以不会报错, 

然而第二次调用 think.model('model'),  由于取了models里的缓存. 但是`think-sequelize`还是会遍历并创建relations到`source.associations`中, 但是这时`hasAlias=true`了 所以sequelize会报错. 不知道这样有没有理解

**Comment by lushijie** [comment]
think-sequelize@1.0.6 问题修复了。抽空再深入研究一下，可能解决方案会变。谢谢反馈

**Comment by lushijie** [comment]
think-sequelize@1.0.7 这个版本修复了。抽空深入一下这个模块，还有些东西要优化。谢谢

**Comment by lushijie** [comment]
ping @callmez

**Comment by callmez** [comment]
感谢修复
