### ISSUE TITLE
think-model使用think-mongo适配时，提示: config.handle must be a function

### ISSUE THREAD

**Issue by SinRedemption** [thinkjs/thinkjs#948]
## DESC
新手！！！

根据 https://thinkjs.org/zh-cn/doc/3.0/mongo.html 的配置连接mongodb，但一直提示 config.handle must be a function，本想参照mysql的配置，但连接数据库的时候，日志显示是mysql://开头，这样无法连接到mongo

### ENV

OS Platform:

macOS High Sierra

Node.js Version:

node 8.9

ThinkJS Version:

ThinkJS 3.2.3
think-mongo 1.0.5

### code

extend配置：
```js
const view = require('think-view');
const model = require('think-model');
const cache = require('think-cache');
const session = require('think-session');
const mongo = require('think-mongo');

module.exports = [
    view,                 // make application support view
    model(think.app),
    mongo(think.app),
    cache,
    session
];
```
adapter配置：
```js
/**
 * model adapter config
 * @type {Object}
 */
exports.model = {
    type: 'mongo', // 默认使用的类型，调用时可以指定参数切换
    common: { // 通用配置
        logConnect: true, // 是否打印数据库连接信息
        logger: msg => think.logger.info(msg) // 打印信息的 logger
    },
    mongo: {
        host: '127.0.0.1',
        port: 27017,
        user: '',
        password: '',
        database: 'users',
        options: ''
    }
};
```

### error message

```
{ AssertionError [ERR_ASSERTION]: config.handle must be a function
    at new Model (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-model/lib/model.js:25:5)
    at model (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-model/index.js:31:22)
    at Object.model (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-model/index.js:67:26)
    at module.exports.model (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-model/index.js:61:25)
    at new module.exports (/Users/sand/Workspace/projects/MAP/ms-user/src/controller/api/rest.js:13:31)
    at new module.exports (/Users/sand/Workspace/projects/MAP/ms-user/src/controller/api/v1/users/index.js:3:18)
    at /Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-controller/index.js:36:22
    at dispatch (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/koa-compose/index.js:42:32)
    at next (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/koa-compose/index.js:43:18)
    at /Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-logic/index.js:30:14
    at dispatch (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/koa-compose/index.js:42:32)
    at Router.next (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/koa-compose/index.js:43:18)
    at Router.parseRule (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-router/router.js:246:17)
    at Router.run (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-router/router.js:266:19)
    at router (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-router/index.js:100:21)
    at dispatch (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/koa-compose/index.js:42:32)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' } { request: 
   { method: 'GET',
     url: '/api/v1/users',
     header: 
      { host: '127.0.0.1:8080',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
        accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'en-US,en;q=0.8,zh;q=0.6,zh-CN;q=0.4,en-GB;q=0.2,zh-TW;q=0.2',
        'cache-control': 'max-age=0',
        'proxy-connection': 'keep-alive',
        'upgrade-insecure-requests': '1',
        'x-lantern-version': '4.1.2' } },
  response: 
   { status: 404,
     message: 'Not Found',
     header: { 'x-powered-by': 'thinkjs-3.2.3' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/api/v1/users',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
```

**Comment by lushijie** [comment]
controller 可否继承了 think.Mongo?
实例化对象的时候是否错用了 .model 方法，这里应该使用 .mongo 方法。

**Comment by SinRedemption** [comment]
@lushijie 这是我的user.js模型文件的实现：

```js
module.exports = class extends think.Mongo {
    getList() {
        return this.field('name').select();
    }
};
```
跟踪代码时，问题应该是连接到Mongodb时出现错误，还未进入模型。think-model/lib/model.js文件在创建对象时，会判断适配器配置的handle属性，代码如下：
```js
constructor(modelName = '', config = {}) {
    if (helper.isObject(modelName)) {
      [modelName, config] = ['', modelName];
    }
    assert(helper.isFunction(config.handle), 'config.handle must be a function');
    this.config = config;
    this.modelName = modelName;
    this.options = {};
    this[RELATION] = new Relation(this);
  }
```

但这个属性文档上没有说明，对比了think-model-mysql的实现，它有一个继承自Abstract的类，但mongo没有，是我的代码必须自己实现一个mongo相关的handle?

**Comment by zhengqingxin** [comment]
@SinRedemption 用 think-mongo 就不要用 think-model 了，在 extend.js 里把 think-model 的配置都删掉试试。

**Comment by SinRedemption** [comment]
@zhengqingxin 试了在extend.js中只保留mongo的配置，但在rest控制器中会调用this.model方法，所以会出现 this.model must be a function 错误：
{ AssertionError [ERR_ASSERTION]: this.model must be a function
    at new module.exports (/Users/sand/Workspace/projects/MAP/ms-user/src/controller/api/rest.js:12:5)
    at new module.exports (/Users/sand/Workspace/projects/MAP/ms-user/src/controller/api/v1/users/index.js:3:18)
    at /Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-controller/index.js:36:22
    at dispatch (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/koa-compose/index.js:42:32)
    at next (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/koa-compose/index.js:43:18)
    at /Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-logic/index.js:30:14
    at dispatch (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/koa-compose/index.js:42:32)
    at Router.next (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/koa-compose/index.js:43:18)
    at Router.parseRule (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-router/router.js:246:17)
    at Router.run (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-router/router.js:266:19)
    at router (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-router/index.js:100:21)
    at dispatch (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/koa-compose/index.js:42:32)
    at next (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/koa-compose/index.js:43:18)
    at parseBody.then.body (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/think-payload/index.js:59:14)
    at tryCatcher (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sand/Workspace/projects/MAP/ms-user/node_modules/bluebird/js/release/promise.js:502:31)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' } { request: 
   { method: 'GET',
     url: '/api/v1/users',
     header: 
      { host: '127.0.0.1:8080',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
        accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'en-US,en;q=0.8,zh;q=0.6,zh-CN;q=0.4,en-GB;q=0.2,zh-TW;q=0.2',
        'cache-control': 'max-age=0',
        'proxy-connection': 'keep-alive',
        'upgrade-insecure-requests': '1',
        'x-lantern-version': '4.1.2' } },
  response: 
   { status: 404,
     message: 'Not Found',
     header: { 'x-powered-by': 'thinkjs-3.2.3' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/api/v1/users',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
依然不行

**Comment by zhengqingxin** [comment]
把 `this.model` 都改成 `this.mongo`

**Comment by zhengqingxin** [comment]
后续 think-cli 2.0 会在创建 rest api 的时候，如果用mongo，会将 this.model 改成 this.mongo，现在暂时手动修改下吧，静待 think-cli 2.0 发布。

**Comment by SinRedemption** [comment]
@zhengqingxin 确实是这个问题，目前手动修改生成的rest.js文件，然后就可以了...
