### ISSUE TITLE
使用关联查询 子表的where怎么传入

### ISSUE THREAD

**Issue by liuhuanhui** [thinkjs/thinkjs#965]
使用关联查询 子表的where怎么传入呢   官网找不到相关传入的方式

**Comment by welefen** [comment]
https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-548 这里有配置 where 的文档

**Comment by liuhuanhui** [comment]
where的条件值是动态传入的呢？怎么传到 get relation() 里面

**Comment by welefen** [comment]
@liuhuanhui where 是支持函数的，可以在具体的方法里把条件放到 this 对象上，然后在 where 函数里使用，如：

```js
get relation() {
  return {
    a: {
      where: function() {
        return {id: this.xxx}
      }
    }
  }
}
getSth(data) {
  this.xxx = data.xxx;
  // do something
}
```

**Comment by liuhuanhui** [comment]
还是不行哦Unknown column 'undefined' in 'where clause'

**Comment by welefen** [comment]
@liuhuanhui 提供下详细的代码

**Comment by liuhuanhui** [comment]
action:
 /**
         * 登录
         */
    async loginAction() {
        let activity_id = this.post('activity_id')
          return this.success(await think.model('user').getLoginInfo(activity_id))
}


model:
  getLoginInfo(activity_id) {
        this.activity_id = activity_id
        return think.model('user').where({
            activity_id: activity_id
        }).find()
    }
 get relation() {
        return {
            myGifts: {
                type: think.Model.HAS_MANY,
                model: 'giftsReceive',
                key: 'wwid',
                fkey: 'user_id',
                where: function() {
                     return { activity_id: this.activity_id }
                }
            },
            myAddress: {
                type: think.Model.HAS_MANY,
                model: 'address',
                key: 'wwid',
                fkey: 'user_id'
            }
        }
    }

**Comment by welefen** [comment]
@liuhuanhui this 的问题，where 用箭头函数吧。 

```js
where: () => {
  return {}
}
```

**Comment by liuhuanhui** [comment]
一样呀 555~

**Comment by welefen** [comment]
@liuhuanhui 是报错，还是查的数据有问题？
* 提供下 think-model 模板的版本
* 如果是查的数据有问题，提供下控制台下打印的 SQL 语句

**Comment by liuhuanhui** [comment]
`{
  "name": "thinkjs-application",
  "description": "application created by thinkjs",
  "version": "1.0.0",
  "scripts": {
    "start": "node development.js",
    "compile": "babel --no-babelrc src/ --presets think-node --out-dir app/",
    "lint": "eslint src/",
    "lint-fix": "eslint --fix src/"
  },
  "dependencies": {
    "moment": "^2.19.2",
    "think-cache": "^1.0.0",
    "think-cache-file": "^1.0.8",
    "think-logger3": "^1.0.0",
    "think-model": "^1.0.0",
    "think-model-mysql": "^1.0.0",
    "think-session": "^1.0.0",
    "think-session-file": "^1.0.5",
    "think-view": "^1.0.0",
    "think-view-nunjucks": "^1.0.1",
    "thinkjs": "^3.0.0"
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-preset-think-node": "^1.0.0",
    "node-notifier": "^5.0.2",
    "think-watcher": "^3.0.0",
    "think-inspect": "0.0.2",
    "think-babel": "^1.0.3",
    "eslint": "^4.2.0",
    "eslint-config-think": "^1.0.0"
  },
  "repository": "",
  "license": "MIT",
  "engines": {
    "node": ">=6.0.0"
  },
  "readmeFilename": "README.md",
  "thinkjs": {
    "metadata": {
      "name": "api",
      "description": "A Speike project",
      "author": "DESKTOP-NNIB5J0\\liuhuanhui <liuhuanhui@live.cn>"
    },
    "projectName": "api",
    "templateName": "C:\\Users\\liuhuanhui\\AppData\\Roaming\\npm\\node_modules\\think-cli\\default_template",
    "isMultiModule": false
  }
}`

是直接500错误了

**Comment by welefen** [comment]
@liuhuanhui 具体错误信息呢？不是要 package.json 里的，而是 node_modules 下实际安装的版本

**Comment by liuhuanhui** [comment]
也是1.0呀  `[2017-11-23 21:36:53.550] [21308] [INFO] - SQL: SELECT * FROM `giftsReceive` WHERE ( `activity_id` = undefined ) AND ( `user_id` = '152036340' ), Time: 40ms
{ Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
    at Query.Sequence._packetToError (D:\projects\gift\api\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (D:\projects\gift\api\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\projects\gift\api\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (D:\projects\gift\api\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (D:\projects\gift\api\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\projects\gift\api\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
    --------------------
    at Protocol._enqueue (D:\projects\gift\api\node_modules\mysql\lib\protocol\Protocol.js:141:48)
    at PoolConnection.query (D:\projects\gift\api\node_modules\mysql\lib\Connection.js:208:25)
    at Promise (D:\projects\gift\api\node_modules\think-helper\index.js:83:10)
    at Promise._execute (D:\projects\gift\api\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (D:\projects\gift\api\node_modules\bluebird\js\release\promise.js:473:18)
    at new Promise (D:\projects\gift\api\node_modules\bluebird\js\release\promise.js:77:14)
    at args (D:\projects\gift\api\node_modules\think-helper\index.js:82:12)
    at ThinkMysql.[think-mysql-query] (D:\projects\gift\api\node_modules\think-mysql\index.js:129:12)
    at debounceInstance.debounce (D:\projects\gift\api\node_modules\think-mysql\index.js:196:29)
    at Debounce.debounce (D:\projects\gift\api\node_modules\think-debounce\index.js:18:30)
    at getConnection.then.connection (D:\projects\gift\api\node_modules\think-mysql\index.js:195:33)
    at tryCatcher (D:\projects\gift\api\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\projects\gift\api\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (D:\projects\gift\api\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (D:\projects\gift\api\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (D:\projects\gift\api\node_modules\bluebird\js\release\promise.js:683:18)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  index: 0 } { request:
   { method: 'POST',
     url: '/index/login',
     header:
      { cookie: 'Hm_lvt_8a0c252c1af871469229aa2bdb1449c1=1504879023',
        'accept-language': 'zh-CN,zh;q=0.9',
        'accept-encoding': 'gzip, deflate, br',
        referer: 'http://localhost:8080/',
        'content-type': 'application/json;charset=UTF-8',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36',
        origin: 'http://localhost:8080',
        accept: 'application/json, text/plain, */*',
        'content-length': '53',
        connection: 'close',
        host: 'localhost:8080' } },
  response:
   { status: 200,
     message: 'OK',
     header: { 'x-powered-by': 'thinkjs-3.2.3' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/index/login',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }`

**Comment by liuhuanhui** [comment]
hello  还是无解吗～

**Comment by lizheming** [comment]
```js
get relation() {
  return {
    a: {
      where: () => ({id: this.id})
    }
  }
}

getSth(data) {
  this.id = data.id;
  // do something
}
```
