### ISSUE TITLE
logger advanced模式下报appenderList.forEach is not a function错误

### ISSUE THREAD

**Issue by jnotnull** [thinkjs/thinkjs#983]
## DESC
参考https://thinkjs.org/zh-cn/doc/3.0/logger.html#toc-1f3，
logger advanced模式下报appenderList.forEach is not a function错误
### ENV

OS Platform:
mac
Node.js Version:
8.9.1
ThinkJS Version:
3.0
think-cli@1.0.13
### code

```js
const path = require('path');
const {DateFile, Basic} = require('think-logger3');

exports.logger = {
    type: 'advanced',
    advanced: {
        handle: Basic,
        appenders: {
            everything: {
                type: 'file',
                filename: path.join(think.ROOT_PATH, 'logs/all-the-logs.log')
            },
            emergencies: {
                type: 'file',
                filename: path.join(think.ROOT_PATH, 'logs/oh-no-not-again.log')
            },
            'just-errors': {
                type: 'logLevelFilter',
                appender: 'emergencies',
                level: 'error'
            }
        },
        categories: {
            default: {
                appenders: ['just-errors', 'everything'],
                level: 'debug'
            }
        }
    }
};
```

### error message

```
Error: Problem reading log4js config { appenders: 
   { everything: 
      { type: 'file',
        filename: '/Users/jiyanliang/zhiqu/thinkjs3.0/logs/all-the-logs.log' },
     emergencies: 
      { type: 'file',
        filename: '/Users/jiyanliang/zhiqu/thinkjs3.0/logs/oh-no-not-again.log' },
     'just-errors': 
      { type: 'logLevelFilter',
        appender: 'emergencies',
        level: 'error' } },
  categories: { default: { appenders: [Array], level: 'debug' } },
  type: 'advanced' }. Error was "appenderList.forEach is not a function" (TypeError: appenderList.forEach is not a function
    at configureAppenders (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/log4js/lib/log4js.js:254:18)
    at configureOnceOff (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/log4js/lib/log4js.js:315:7)
    at Object.configure (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/log4js/lib/log4js.js:376:3)
    at ConsoleLogger.configure (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/think-logger3/src/adapter/base.js:31:19)
    at ConsoleLogger.setLogger (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/think-logger3/src/adapter/base.js:38:10)
    at new ConsoleLogger (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/think-logger3/src/adapter/console.js:18:10)
    at new Logger (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/think-logger3/src/index.js:11:20)
    at thinkLoader.loadAll (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/lib/loader.js:100:20)
    at Application.run (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/lib/application.js:197:18)
    at Object.<anonymous> (/Users/jiyanliang/zhiqu/thinkjs3.0/development.js:10:10)
    at Module._compile (module.js:632:14)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10))
    at configureOnceOff (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/log4js/lib/log4js.js:321:13)
    at Object.configure (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/log4js/lib/log4js.js:376:3)
    at ConsoleLogger.configure (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/think-logger3/src/adapter/base.js:31:19)
    at ConsoleLogger.setLogger (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/think-logger3/src/adapter/base.js:38:10)
    at new ConsoleLogger (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/think-logger3/src/adapter/console.js:18:10)
    at new Logger (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/think-logger3/src/index.js:11:20)
    at thinkLoader.loadAll (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/lib/loader.js:100:20)
    at Application.run (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/lib/application.js:197:18)
    at Object.<anonymous> (/Users/jiyanliang/zhiqu/thinkjs3.0/development.js:10:10)
    at Module._compile (module.js:632:14)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
```

### more description

// your detail description

**Comment by jnotnull** [comment]
@lizheming 有问题不，大概啥时候能好呢，坐等 😄

**Comment by lizheming** [comment]
你本地的 log4js 版本有问题，think-logger 需要 2.0 版本的 log4js 的支持，但是你目前报错看应该装的是 1.x 版本的：https://github.com/log4js-node/log4js-node/blob/f7ec3ccf82dd9eda1fd617559f94373e42399c68/lib/log4js.js#L254

你是正常 `npm install` 安装的？感觉不科学啊，我的模块已经指定了 `log4js` 安装 `2.3.11` 以上的版本才对 https://github.com/thinkjs/think-logger/blob/master/package.json#L29。

**Comment by lizheming** [comment]
ping @jnotnull

**Comment by jnotnull** [comment]
这两天忙搞前端，明天我验证下 不好意思 @lizheming

**Comment by jnotnull** [comment]
是我Logger版本太低了，当前我看指定的是^1.1.0
`{
  "_args": [
    [
      "think-logger3@1.0.7",
      "/Users/jiyanliang/zhiqu/thinkjs3.0"
    ]
  ],
  "_from": "think-logger3@1.0.7",
  "_id": "think-logger3@1.0.7",
  "_inBundle": false,
  "_integrity": "sha512-0VMNEFEV01dJfB5IrpwCH8Q159eAiAtP9CdcoC4SePvV5Ozui4q28+o9K1qR4wgL91c0IPkemckgo9NqSsqLpA==",
  "_location": "/think-logger3",
  "_phantomChildren": {},
  "_requested": {
    "type": "version",
    "registry": true,
    "raw": "think-logger3@1.0.7",
    "name": "think-logger3",
    "escapedName": "think-logger3",
    "rawSpec": "1.0.7",
    "saveSpec": null,
    "fetchSpec": "1.0.7"
  },
  "_requiredBy": [
    "/",
    "/thinkjs"
  ],
  "_resolved": "https://registry.npmjs.org/think-logger3/-/think-logger3-1.0.7.tgz",
  "_spec": "1.0.7",
  "_where": "/Users/jiyanliang/zhiqu/thinkjs3.0",
  "author": {
    "name": "lizheming"
  },
  "bugs": {
    "url": "https://github.com/thinkjs/think-logger/issues"
  },
  "dependencies": {
    "log4js": "^1.1.0"
  },
  "description": "logger for ThinkJS 3.x",
  "devDependencies": {
    "ava": "^0.18.2",
    "eslint": "^4.2.0",
    "eslint-config-think": "^1.0.1",
    "nyc": "^10.1.2",
    "sandboxed-module": "^2.0.3"
  },
  "homepage": "https://github.com/thinkjs/think-logger#readme",
  "keywords": [
    "thinkjs",
    "logger",
    "log4js"
  ],
  "license": "MIT",
  "main": "./src",
  "name": "think-logger3",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/thinkjs/think-logger.git"
  },
  "scripts": {
    "eslint": "eslint ./src",
    "prepublish": "npm test",
    "test": "npm run eslint && npm run test-cov",
    "test-cov": "nyc ava test/ && nyc report --reporter=html"
  },
  "version": "1.0.7"
}
`

**Comment by lizheming** [comment]
哦哦，对 advanced 是在 1.1.1 上加的，我待会补下文档，sorry~~

**Comment by jnotnull** [comment]
我刚手工改了下版本号，发现log4js是作为think-logger3的私有依赖包安装了，这个是故意这么做的么？
log4js路径：think-logger3/node_modules/log4js

**Comment by lizheming** [comment]
不是，应该是你手动改的版本号重新安装，之前的 log4js 没有删掉，两个版本不一致所以 npm 给装到了 think-logger3 内部了。

**Comment by jnotnull** [comment]
thinkjs升级到3.2.4之后debug启动又报了这个错了，我要重新开贴么？
```
Unhandled rejection TypeError: process.send is not a function
    at Master.sendInspectPort (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/think-cluster/lib/master.js:161:15)
    at promise.then.data (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/think-cluster/lib/master.js:170:12)
    at tryCatcher (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:628:18)
    at PromiseArray._resolve (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:564:26)
    at Promise._settlePromise0 (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
(node:38689) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:38689) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
```

**Comment by lizheming** [comment]
用 `inspect` 启动了？这个我不太清楚了，重新开个 issue 说一下吧。

**Comment by jnotnull** [comment]
en  已经另开issue了。另外我如果想使用TRACE MARK这些级别在哪里进行扩展呢

```ALL: new Level(Number.MIN_VALUE, 'ALL', 'grey'),
    TRACE: new Level(5000, 'TRACE', 'blue'),
    DEBUG: new Level(10000, 'DEBUG', 'cyan'),
    INFO: new Level(20000, 'INFO', 'green'),
    WARN: new Level(30000, 'WARN', 'yellow'),
    ERROR: new Level(40000, 'ERROR', 'red'),
    FATAL: new Level(50000, 'FATAL', 'magenta'),
    MARK: new Level(9007199254740992, 'MARK', 'grey'), // 2^53
    OFF: new Level(Number.MAX_VALUE, 'OFF', 'grey')
```
