### ISSUE TITLE
think-mongoose populate 无法使用

### ISSUE THREAD

**Issue by tjhyupo505** [thinkjs/thinkjs#984]
## DESC
1、model下生成了3个mongoose的类，分别是 grouping、employee、grouping2employee。
2、grouping2employee 中定义了2个ref字段分别指向 grouping 和 employee。
3、通过 grouping2employee 查询数据的时候 populate 对应的 employee，这个时候会报错：Schema hasn't been registered for model "employee"

看起来是全局自动注册的model在populate的时候无效！

### ENV

OS Platform: centos 7.1

Node.js Version: 8.9.1LTS

ThinkJS Version: 3.2.4

### code

```js
// grouping2employee.js

module.exports = class extends think.Mongoose {
  get schema() {
    const schema = new think.Mongoose.Schema(
      {
        grouping: {type: think.Mongoose.ObjectId, ref: 'group'}, // 班组，ref后可以通过populate关联查询。
        employee: {type: think.Mongoose.ObjectId, ref: 'employee'}, // 工人
        created: {type: Date, default: Date.now},
        updated: {type: Date, default: Date.now}
      }
    );

    return schema;
  }
};

// employee.js
module.exports = class extends think.Mongoose {
  get schema() {
    const schema = new think.Mongoose.Schema(
      {
        name: {type: String, unique: true}, 
        mobile: String,
        status: {type: Boolean, default: true}, 
        resign_datetime: {type: Date, default: Date.now}, 
        created: {type: Date, default: Date.now},
        updated: {type: Date, default: Date.now}
      }
    );
     
    return schema;
  }
};

// controller 中调用的方法
const grouping2employeeModel = this.model('grouping2employee');
const data = await grouping2employeeModel.find().populate('employee');

```

### error message

{ MissingSchemaError: Schema hasn't been registered for model "employee".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/home/andy/workspace/thinkjs/znaqm/node_modules/mongoose/lib/error/missingSchema.js:20:11)
    at NativeConnection.Connection.model (/home/andy/workspace/thinkjs/znaqm/node_modules/mongoose/lib/connection.js:1079:11)
    at getModelsMapForPopulate (/home/andy/workspace/thinkjs/znaqm/node_modules/mongoose/lib/model.js:3669:20)
    at populate (/home/andy/workspace/thinkjs/znaqm/node_modules/mongoose/lib/model.js:3194:15)
    at _populate (/home/andy/workspace/thinkjs/znaqm/node_modules/mongoose/lib/model.js:3162:5)
    at Function.Model.populate (/home/andy/workspace/thinkjs/znaqm/node_modules/mongoose/lib/model.js:3122:5)
    at Immediate.cb (/home/andy/workspace/thinkjs/znaqm/node_modules/mongoose/lib/query.js:1295:17)
    at Immediate._onImmediate (/home/andy/workspace/thinkjs/znaqm/node_modules/mquery/lib/utils.js:137:16)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
  message: 'Schema hasn\'t been registered for model "employee".\nUse mongoose.model(name, schema)',
  name: 'MissingSchemaError' } { request: 
   { method: 'GET',
     url: '/group?id=5a20ec3c89ce3ee143a1d39a',
     header: 
      { 'cache-control': 'no-cache',
        'postman-token': '8562c1e0-92c0-4012-982d-96a5d2a91abc',
        'user-agent': 'PostmanRuntime/6.4.1',
        accept: '*/*',
        host: '192.168.25.130:8360',
        cookie: 'znaqm-session-cookie=7bb835f4-4bdc-4c39-a765-87bc369ee791',
        'accept-encoding': 'gzip, deflate',
        connection: 'keep-alive' } },
  response: 
   { status: 200,
     message: 'OK',
     header: { 'x-powered-by': 'thinkjs-3.2.4' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/group?id=5a20ec3c89ce3ee143a1d39a',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' 

```
// your error message here
```

### more description

// your detail description

**Comment by tjhyupo505** [comment]
1、.populate('think_employee'); 这个方法不管用，只是找不到表中的think_employee字段而没有执行populate。

2、核心发现报错找不到shema是model中的ref字段

**Comment by tjhyupo505** [comment]
改成如下的也不行，依然报错：MissingSchemaError: Schema hasn't been registered for model "think_employee"。
const schema = new think.Mongoose.Schema(
{
grouping: {type: think.Mongoose.ObjectId, ref: 'grouping'},
think_employee: {type: think.Mongoose.ObjectId, ref: 'think_employee'},
created: {type: Date, default: Date.now},
updated: {type: Date, default: Date.now}
}
);

**Comment by tjhyupo505** [comment]
目前看来是怎么把 think-mongoose 的 instance 复用给 mongoose 自己的 populate 方法的问题了。因为所有的model都是注册在了 think-mongoose 的 instance 上，而 mongoose 自己的 populate 方法是mongoose自己的一个实例。好坑啊，麻烦看看怎么包装一下吧，多谢！

**Comment by lushijie** [comment]
```js
// src/controller/mongoose.js
  async testAction() {
    const Grouping2Employee = this.model('mongoose/grouping2employee');
    const data = await Grouping2Employee.find().populate('employee').exec();
    this.success(data);
  }

// src/model/mongoose/grouping2employee.js
get schema() {
    const schema = new think.Mongoose.Schema(
      {
        department: {
          type: think.Mongoose.ObjectId,
          ref: `${this.tablePrefix}department`
        }, 
        employee: {
          type: think.Mongoose.ObjectId,
          ref: `${this.tablePrefix}employee`
        }, 
        name: String
      }
    );
    
   // 手动初始化 ref 对应的模型
    think.mongoose('mongoose/employee', {type: 'mongoose'}); 
    think.mongoose('mongoose/department', {type: 'mongoose'}); 

    return schema;
 }
```

schema 传入think-mongoose 之后 schema 中的 ref 没有做处理所以会出现 `hasn't been registered` 问题，暂时先这样手动初始化一下，后续优化。

**Comment by tjhyupo505** [comment]
希望能尽快优化一下吧，引起各种bug啊！除了这个地方使用，另外比如在 department 的schema 的class中定义一个方法使用this.model('employee')同样会报错：

> MissingSchemaError: Schema hasn't been registered for model "employee".

例如下面这个用作测试的代码例子：

`
// department.js
module.exports = class extends think.Mongoose {
  get schema() {
    const schema = new think.Mongoose.Schema(
      {
        name: {type: String, unique: true}, 
        created: {type: Date, default: Date.now},
        updated: {type: Date, default: Date.now}
      }
    );

    return schema;
  }

async findEmployees(employee_id) {
  const data = await this.model('employee').find({ _id: employee_id });
  return (data);
};
  
};
`

**Comment by lushijie** [comment]
你把这里的 this.model 也替换为 think.mongoose 试试吧😄

**Comment by tjhyupo505** [comment]
1、最后面一个问题this.model 也替换为 think.mongoose可以解决。多谢！
2、populate的问题不行，还是只能通过在shema中手动初始化 ref 对应的模型
    think.mongoose('mongoose/employee', {type: 'mongoose'}); 
    think.mongoose('mongoose/department', {type: 'mongoose'});

期待think-mongoose后续版本优化。

**Comment by lushijie** [comment]
恩，目前是这样的，关于 ref 的问题我们稍后讨论一下，看看怎么处理会比较好。

**Comment by zengqingsong** [comment]
还有一个问题所有的虚拟字段不能用

**Comment by lushijie** [comment]
@zengqingsong 指的是什么？来段代码吧

**Comment by zengqingsong** [comment]
我搞错了，虚拟字段可以用了。think-mongoose更详细的用法可以参考我的一个项目，http:/gitee.com/zengqs/think-admin

**Comment by zengqingsong** [comment]
https://m.gitee.com/zengqs/thinkjs-admin

**Comment by zengqingsong** [comment]
增加了几个方法可以考虑增加到官方的think-mongoose模块中。

**Comment by welefen** [comment]
@zengqingsong  欢迎提 pr

**Comment by lushijie** [comment]
暂时只支持手动初始化 ref 对应的模型， 如 commented on 2 Dec 2017 提到的
