### ISSUE TITLE
think-mongoose 自定义方法无法调用？

### ISSUE THREAD

**Issue by tjhyupo505** [thinkjs/thinkjs#985]
## DESC
参考think-mongoose的例子在model中自定义了一个方法。但是调用的时候报错说方法不存在。

### ENV

OS Platform: centos 7.1

Node.js Version: 8.9.1 LTS

ThinkJS Version: 3.2.4

### code

```js

// grouping.js
// model定义，参考的think-mongoose说明中的例子
module.exports = class extends think.Mongoose {
  get schema() {
    const schema = new think.Mongoose.Schema(
      {
        name: {type: String, unique: true}
      }
    );
   
    schema.methods.findEmployees = function(cb) {
      return this.model('grouping').find({ name: '白班' }, cb);
    };

    
    return schema;
  }
};

// controller中调用方法1
const grouping = this.model('grouping');
let data = await grouping.findEmployees();

// controller中调用方法2
const grouping = this.model('grouping');
grouping.findEmployees(function(err, groupings) {
  console.log(groupings);
});

```

### error message

TypeError: grouping.findEmployees is not a function
    at module.exports.indexAction (/home/andy/workspace/thinkjs/znaqm/src/controller/group.js:18:14)
    at promise.then.data (/home/andy/workspace/thinkjs/znaqm/node_modules/think-controller/index.js:53:32)
    at tryCatcher (/home/andy/workspace/thinkjs/znaqm/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/andy/workspace/thinkjs/znaqm/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/andy/workspace/thinkjs/znaqm/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromiseCtx (/home/andy/workspace/thinkjs/znaqm/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:596:10)
    at Async._drainQueue (/home/andy/workspace/thinkjs/znaqm/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/home/andy/workspace/thinkjs/znaqm/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/andy/workspace/thinkjs/znaqm/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5) { request: 
   { method: 'GET',
     url: '/group?id=5a20ec3c89ce3ee143a1d39a',
     header: 
      { 'cache-control': 'no-cache',
        'postman-token': '2c51ec91-246c-4c29-99b5-38dbb5876ffd',
        'user-agent': 'PostmanRuntime/6.4.1',
        accept: '*/*',
        host: '192.168.25.130:8360',
        cookie: 'znaqm-session-cookie=7bb835f4-4bdc-4c39-a765-87bc369ee791',
        'accept-encoding': 'gzip, deflate',
        connection: 'keep-alive' } },
  response: 
   { status: 200,
     message: 'OK',
     header: { 'x-powered-by': 'thinkjs-3.2.4' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/group?id=5a20ec3c89ce3ee143a1d39a',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }

```
// your error message here
```

### more description

// your detail description

**Comment by welefen** [comment]
schema 上的方法需要自己再实例化才能使用，这是 mongoose 奇葩的设计导致的（加了很多静态方法，但有些方法又需要自己实例化才能使用）

```js
const Cls = this.mongoose('grouping');
const instance = new Cls();
const result = instance.findEmployees();
```

且这里还有个问题，如果数据表有前缀，那么在 schema 里的方法调用(如：this.model('grouping')) 需要自己带上数据表前缀（如：this.model('think_grouping')），因为这里的 model 方法是 mongoose 的。

所以尽量不要把方法定义在 schema 上，可以直接在类里定义。

```js
module.exports = class extends think.Mongoose {
  get schema() {
    const schema = new think.Mongoose.Schema(
      {
        name: {type: String, unique: true}
      }
    );
    return schema;
  }
  findEmployees() {
      return this.find();
  }
};
```

**Comment by tjhyupo505** [comment]
采用第二种方法解决了，多谢！
