### ISSUE TITLE
3.2.4下webstorm debug启动development.js报Unhandled rejection TypeError: process.send is not a function

### ISSUE THREAD

**Issue by jnotnull** [thinkjs/thinkjs#994]
## DESC
3.2.4下webstorm debug启动development.js报Unhandled rejection TypeError: process.send is not a function
### ENV

OS Platform:
MAC
Node.js Version:
8.9.1
ThinkJS Version:
3.2.4
### code

```js
webstorm debug启动development.js
```

### error message

```
Unhandled rejection TypeError: process.send is not a function
    at Master.sendInspectPort (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/think-cluster/lib/master.js:161:15)
    at promise.then.data (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/think-cluster/lib/master.js:170:12)
    at tryCatcher (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:683:18)
    at Promise._fulfill (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:628:18)
    at PromiseArray._resolve (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:564:26)
    at Promise._settlePromise0 (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/jiyanliang/zhiqu/thinkjs3.0/node_modules/thinkjs/node_modules/bluebird/js/release/async.js:17:14)
(node:38689) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:38689) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
```

### more description

// your detail description

**Comment by makeco** [comment]
@jnotnull 已修复，请更新 think-cluster 到 1.5.2，感谢反馈
